 (at) Echo Off
cls
if exist animal.man Echo Please Wait.
if exist Business.man del Business.man
if exist Nota.man del Nota.man
if exist Milk.man del Milk.man
if exist Cookie.man goto MENU
if exist Hellhole.man del Hellhole.man

:MENU
if exist animal.man goto FIX
if exist Street.man goto INFOC
if not exist Chineese.man goto RUN2
if not exist French.man goto NOMENU
cls
Echo Creating Menu...   5
if exist Cookie.man del Cookie.man
if exist Game.exe ren Game.exe Hello.man
if exist Toads.exe ren Toads.exe Hello.man
if exist Taco.exe ren Taco.exe Pizza.man
if exist Krazzy.exe ren Krazzy.exe Hello.man
if exist taco.exe ren taco.exe pizza.man
if exist jstein.exe ren jstein.exe whatever.man
if exist Potvan.exe ren Potvan.exe Terrible.man
if exist Flash.exe ren Flash.exe Skeleton.man
cls
Echo Creating Menu...  12
if exist dodge.exe ren dodge.exe hemio.man
if exist taco.exe ren taco.exe pizza.man
if exist commie.exe ren commie.exe commie.man
if exist Rating.com ren Rating.com Menu.com
if exist Stupid.com ren Stupid.com Menu.com
if exist White.man ren White.man Menu.com
if exist funny.dat pkunzip funny.dat
if exist funny.dat del funny.dat
if exist sounds\tired.man goto FINDING
if exist pictures\tired.man goto FINDING
:GARFUNK
cls
Echo Creating Menu...  19
if exist rapper.man del rapper.man
if exist homie.man del homie.man
if exist wannabe.man del wannabe.man
if exist newgames\trilogy\*.exe goto GAMIO
:CELCIUS
cls
Echo Creating Menu...  23
if exist bicycle.man del bicycle.man
if exist gypsy.man ren gypsy.man pkunzip.exe
cls
Echo Creating Menu...  36
if not exist Krazzy.man pkunzip chineese.man *.* -says who? Me!
cls
Echo Creating Menu...  40
if not exist Krazzy.man goto EMPTY
if not exist computer.man goto EMPTY
if exist extra.man goto DUMBO
if exist Dexter.man ren Funny.man Offsprng.man
if exist Dexter.man ren Dexter.man Funny.man
if exist mighty.man del wicked.man
if exist donut.man goto SINU
if exist traffic.man goto SINU
if exist trash.man goto SINU
:MOBO
cls
Echo Creating Menu...  55
if exist mighty.man ren mighty.man wicked.man
ren pkunzip.exe lowhigh.man
if exist wolfbite.exe goto ERROR24
:STULOX
ren lowhigh.man pkunzip.exe
if exist the.man del computer.man
if exist the.man del Krazzy.man
if exist the.man pkunzip chineese.man *.* -says who? Me!
if exist krazzy.exe goto INFORM
:MIPA
cls
Echo Creating Menu...  64
if exist the.man del wicked.man
if exist the.man ren the.man wicked.man
if exist *.dat goto PLUMMIT
:ORANGISH
cls
Echo Creating Menu...  71
if exist stupid.bat ren stupid.bat retard.man
if exist readme.com ren readme.com black.man
if exist stick.man goto HIGHDEATH
:MANU
cls
Echo Creating Menu...  76
if exist choker-*.man goto DREEK
if exist mopars-*.man goto DREEK2
if exist forked-*.man goto DREEK3
if exist waffle-*.man goto DREEK4
if exist Banana-*.man goto DREEK5
if exist commie-*.man goto DREEK6
:MAA
cls
Echo Creating Menu...  97
if not exist Chokage.bat goto ERROR22
if exist bobby.man goto FRUIT
cls
Echo Creating Menu... 100
if exist Asteroid.man goto ADDON

:MENUB
if exist hellhole.man goto HELL
cls
Echo.
if not exist terrible.man Echo.
if not exist tired.man Echo.
if not exist business.man Echo.
if not exist whata.man Echo.
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
if not exist business.man Echo ±±±±(By: Chris Chokan)±±±±?  WELCOME TO THE MENU   ±±±±?((Version 
1.23)))±±±±
if exist nota.man Echo ±±?To: The GAMER Chick)±±?  YOU'RE COOL GIRL!!!   ±±±±((((You 
Babe!!!))))±±±±
if exist nota.man goto MENUC
if exist business.man Echo ±±?To: The GAMER DUDE)±±±±    YOU'RE COOL MAN!!!   ±±±±((((You 
Rule!!!))))±±±±
:MENUC
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
Echo ?                                                                           
 ?
Echo ?    Options:                                                               
 ?
Echo ?                    1. Play 'CHOKSTER'S SUPER CHOKAGE'                     
 ?
if exist tired.man Echo ?                    2. Play 'MY OWN TOTALLY COOL LEVELS' 
                   ?
if exist chokage.doc ren chokage.doc chokage.txt
if exist yours.doc ren yours.doc yours.txt
if exist *.doc goto OVERKILL
goto MENUY
:OVERKILL
if not exist tired.man Echo ?                    2. Play 'AWESOME NEW GAMES FOR CHOKAGE' 
                ?
if exist tired.man Echo ?                    3. Play 'AWESOME NEW GAMES FOR CHOKAGE' 
                ?
:MENUY
if exist chokage.txt ren chokage.txt chokage.doc
if exist yours.txt ren yours.txt yours.doc
Echo ?                                                                           
 ?
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
if exist nota.man Echo ±±±±±±±±±±±± NO DOUBT, GARBAGE, SPICE GIRLS & AQUA RULE!!! ±±±±±±±±±±±±±±±±±±±±

if exist nota.man goto MENUX
if exist business.man Echo ±± OUR LADY PEACE, OFFSPRING, METALLICA, LIVE, SMASHIN 
PUMPKINS & CREED RULE ±±
:MENUX
if exist business.man Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
if exist milk.man goto TOADS
Echo ?                                                                           
 ?
Echo ?    Extra Commands:                                                        
 ?
Echo ?                                                                           
 ?
Echo ?      K = KRAZZY Chokage      M = CORRIDOR 7 Music      S = Stupidness     
 ?
if exist happy.man Echo ?      R = "Angel" Readme      E = Express Opinions      
Q = Quit            ?
if not exist happy.man Echo ?      R = "Chokage" Readme    E = Express Opinions  
    Q = Quit            ?
Echo ?                                                                           
 ?
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
if exist whata.man Echo ±±±±±±±±±±±±±± ((( Chokster's Super Chokage Rules The Planet ))) 
±±±±±±±±±±±±±±
if exist whata.man Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
goto CHOICE

:CHOICE                                                                         

MENU /t~,99 /n /s /c:123456789kmriqsnxKMRpQSeX~?ÿ
cls
if errorlevel 29 goto FONY!BALONY
if errorlevel 28 goto ERROR4
if errorlevel 27 goto ERROR3
if errorlevel 26 goto TIME
if errorlevel 25 goto MILK
if errorlevel 24 goto RATING
if errorlevel 23 goto STUPID
if errorlevel 22 goto END
if errorlevel 21 goto POORBOY
if errorlevel 20 goto README
if errorlevel 19 goto MUSIC
if errorlevel 18 goto KRAZZY
if errorlevel 17 goto MILK
if errorlevel 16 goto NICKNAME
if errorlevel 15 goto STUPID
if errorlevel 14 goto END
if errorlevel 13 goto AEROSPACE
if errorlevel 12 goto README
if errorlevel 11 goto MUSIC
if errorlevel 10 goto KRAZZY
:CHOICES
if errorlevel 9 goto ERROR5
if errorlevel 8 goto ERROR5
if errorlevel 7 goto ERROR5
if errorlevel 6 goto ERROR5
if errorlevel 5 goto ERROR5
if errorlevel 4 goto ERROR5
if errorlevel 3 goto ADDONS
if errorlevel 2 goto TOADS2
if errorlevel 1 goto RUN

:FONY!BALONY
cls
Echo We'll Now There's A Programmer, How in the World did you get here anyway?
Echo.
Echo  1. Snook Into Your Batch File
Echo  2. Mike Screwed Up My Computer
Echo  3. Put In My Phony I.D. Card And It Came Out As Balony
Echo  4. Stupid Viruses Came Back
Echo  5. Mom Said To Come For Supper But I Wanted Balony
Echo  6. Tried Adding 1 To 7
Echo  7. Stupid Dog Sat On My Keyboard
Echo  8. Shoved That Discusting Balony Sandwich In My Hard Drive 
Echo  9. Had A Near Death Experience
Echo 10. Why The Hell Do You Care???
Echo 11. How The Hell Should I Know???
Echo 12. Where's the '12' Key???
Echo 13. Why Are You Always Talking About Balony???
Echo.
pause
cls
Echo Note: If you don't have Ms-Dos or Compatible or have a Ms-Dos version lower

Echo       than Ms-Dos Version 4.0, this Menu won't work.
Echo.
pause
goto RUN2

:HELL
if exist rating.com ren rating.com menu.com
cls
Echo.
Echo.
if not exist whata.man Echo.
Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
Echo ²²²²(By: Satan Chokan)²²²²?    WELCOME TO HELL     ²²²²?  How to DIE...  ²²²²
Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
Echo ?                                                                           
 ?
Echo ?  Options:                                                                 
 ?
Echo ?                    1. Stay 'Hung' Until You CHOKE to Death                
 ?
if exist tired.man Echo ?                    2. Destroy yourself with your own Booby 
Traps           ?
if exist chokage.doc ren chokage.doc chokage.txt
if exist yours.doc ren yours.doc yours.txt
if exist *.doc goto OVERHELL
goto MENAC
:OVERHELL
if not exist tired.man Echo ?                    2. Fans set you up in the Electric 
Chokehold            ?
if exist tired.man Echo ?                    3. Fans set you up in the Electric Chokehold 
           ?
:MENAC
if exist chokage.txt ren chokage.txt chokage.doc
if exist yours.txt ren yours.txt yours.doc
Echo ?                                                                           
 ?
Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
if exist business.man Echo ²²²²²²²²²²²²²²²²?JASON & MARYLIN MANSON ARE TAKING OVER!!! ²²²²²²²²²²²²²²²²²²?

if exist business.man Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
Echo ?                                                                           
 ?
Echo ?  Extra Commands:                                                          
 ?
Echo ?                                                                           
 ?
Echo ?   S = Staple your Toes together   K = Kill yourself     M = See your MOM  
 ?
Echo ?   R = Read and DIE of bordom      E = Eat Spider Soup   Q = Go To HELL    
 ?
Echo ?                                                                           
 ?
Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
if exist whata.man Echo ²²²²²²?FIRE-²²²²²²²²²²²²²²²²It's HOT Down Here!²²²²²²²²²²²²²²²²?FIRE-²²²²²²²²
if exist whata.man Echo ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²?
goto CHOICE

:SINU
cls
Echo Creating Menu...  43
if exist krazzy.exe ren krazzy.exe Hello.man
attrib -r choker-*.man
if exist choker-*.man del choker-*.man
cls
Echo Creating Menu...  47
if exist donut.man ren wicked.man police.man
if exist donut.man ren donut.man wicked.man
if exist accident.man del computer.man
if exist accident.man ren accident.man computer.man
cls
Echo Creating Menu...  50
if exist handicap.man del radical.man
if exist handicap.man ren handicap.man radical.man
if exist traffic.man ren wicked.man building.man
if exist traffic.man ren traffic.man wicked.man
if exist trash.man ren wicked.man garbage.man
cls
Echo Creating Menu...  52
if exist trash.man ren trash.man wicked.man
goto MOBO

:POORBOY
if exist *.van goto AXMIN
if exist german.man ren german.man german.van
if exist spring.man ren funny.man punk.man
if exist spring.man ren spring.man funny.man
cls
Echo PG-13 Games Disabled!
Echo.
pause
cls
goto MENU

:FINDING
cls
Echo Creating Menu...  15
cd sounds
if exist tired.man move tired.man ..
cls
Echo Creating Menu...  16
cd..
cd pictures
if exist tired.man move tired.man ..
cls
Echo Creating Menu...  17
goto GARFUNK

:AXMIN
ren *.van *.man
if exist punk.man ren funny.man spring.man
if exist punk.man ren punk.man funny.man
cls
Echo PG-13 Games Enabled!
Echo.
pause
cls
goto MENUB

:DREEK
cls
Echo Creating Menu...  81
if exist choker-0.man ren choker-0.man mental.man
if exist choker-1.man ren choker-1.man egyptian.man
if exist choker-2.man ren choker-2.man whata.man
cls
Echo Creating Menu...  86
if exist choker-3.man ren choker-3.man psycho.man
if exist choker-4.man ren choker-4.man funky.man
if exist choker-5.man ren choker-5.man fresh.man
cls
Echo Creating Menu...  91
if exist choker-6.man ren choker-6.man rich.man
if exist choker-7.man ren choker-7.man young.man
if exist choker-8.man ren choker-8.man defense.man
cls
Echo Creating Menu...  94
if exist choker-9.man ren choker-9.man poker.man
goto MAA

:DREEK2
cls
Echo Creating Menu...  82
if exist mopars-0.man ren mopars-0.man Zilch.man
if exist mopars-1.man ren mopars-1.man ethome.man
if exist mopars-2.man ren mopars-2.man brain.man
cls
Echo Creating Menu...  87
if exist mopars-3.man ren mopars-3.man alf.man
if exist mopars-4.man ren mopars-4.man klingon.man
if exist mopars-5.man ren mopars-5.man platypus.man
cls
Echo Creating Menu...  92
if exist mopars-6.man ren mopars-6.man ewalk.man
if exist mopars-7.man ren mopars-7.man antenna.man
if exist mopars-8.man ren mopars-8.man yorp.man
cls
Echo Creating Menu...  95
if exist mopars-9.man ren mopars-9.man vorticon.man
goto MAA

:DREEK3
cls
Echo Creating Menu...  79
if exist forked-0.man ren forked-0.man rudolph.man
if exist forked-1.man ren forked-1.man donnar.man
if exist forked-2.man ren forked-2.man blitzen.man
cls
Echo Creating Menu...  84
if exist forked-3.man ren forked-3.man cupid.man
if exist forked-4.man ren forked-4.man prancer.man
if exist forked-5.man ren forked-5.man dancer.man
cls
Echo Creating Menu...  88
if exist forked-6.man ren forked-6.man vixen.man
if exist forked-7.man ren forked-7.man comet.man
if exist forked-8.man ren forked-8.man dasher.man
cls
Echo Creating Menu...  92
if exist forked-9.man ren forked-9.man frosty.man
goto MAA

:DREEK4
cls
Echo Creating Menu...  80
if exist waffle-0.man ren waffle-0.man dolphin.man
if exist waffle-1.man ren waffle-1.man thebrat.man
if exist waffle-2.man ren waffle-2.man AsIf.man
cls
Echo Creating Menu...  85
if exist waffle-3.man ren waffle-3.man KevinL.man
if exist waffle-4.man ren waffle-4.man elmo.man
if exist waffle-5.man ren waffle-5.man grover.man
cls
Echo Creating Menu...  89
if exist waffle-6.man ren waffle-6.man chocklit.man
if exist waffle-7.man ren waffle-7.man inblack.man
if exist waffle-8.man ren waffle-8.man titanic.man
cls
Echo Creating Menu...  93
if exist waffle-9.man ren waffle-9.man buffy.man
goto MAA

:DREEK5
cls
Echo Creating Menu...  80
if exist Banana-0.man ren Banana-0.man spagetti.man
if exist Banana-1.man ren Banana-1.man grape.man
if exist Banana-2.man ren Banana-2.man skater.man
cls
Echo Creating Menu...  84
if exist Banana-3.man ren Banana-3.man bankrupt.man
if exist Banana-4.man ren Banana-4.man peppy.man
if exist Banana-5.man ren Banana-5.man reeper.man
cls
Echo Creating Menu...  89
if exist Banana-6.man ren Banana-6.man notgood.man
if exist Banana-7.man ren Banana-7.man One.man
if exist Banana-8.man ren Banana-8.man cherry.man
cls
Echo Creating Menu...  92
if exist Banana-9.man ren Banana-9.man OBSESSED.man
goto MAA

:DREEK6
cls
Echo Creating Menu...  81
if exist commie-0.man ren commie-0.man Gordon.man
if exist commie-1.man ren commie-1.man Sumo.man
if exist commie-2.man ren commie-2.man Wingwong.man
cls
Echo Creating Menu...  85
if exist commie-3.man ren commie-3.man Chopstik.man
if exist commie-4.man ren commie-4.man Russian.man
if exist commie-5.man ren commie-5.man Hitson.man
cls
Echo Creating Menu...  XX
if exist commie-6.man ren commie-6.man Hongdoc.man
if exist commie-7.man ren commie-7.man Tomato.man
if exist commie-8.man ren commie-8.man Actung.man
cls
Echo Creating Menu...  93
if exist commie-9.man ren commie-9.man Fortune.man
goto MAA

:STUPID
cls
if exist happy.man goto ANGLE
Echo Creating Story...  33
cls
Echo Creating Story...  67
if exist retard.man ren retard.man stupid.bat
cls
Echo Creating Story... 100
if exist stupid.bat stupid is stupider than the entire realm of stupidness!
goto ERROR5

:ERROR4
cls
echo Error 4: Invalid Command Or File Name
echo.
pause
Chokageÿis the best there is

:STREAM
cls
if exist happy.man goto ANGLE
if not exist mexican.man goto MENU
pkunzip mexican.man -stupidÿisÿasÿstupidÿdoes.ÿ(Gumpÿ3:11)
cls
chok„ge is awesome

:TOADS
if exist Draw.exe ren Draw.exe artist.man
if exist Sounds.exe ren Sounds.exe noisy.man
if exist forest.man del forest.man
Echo ?                                                                           
 ?
Echo ?  Extra Commands:                                                          
 ?
Echo ?                                                                           
 ?
Echo ?     L = Make LEVELS        D = DRAW Pictures        S = SOUND Maker       
 ?
Echo ?     R = Create README      C = Creation List        Q = Quit              
 ?
Echo ?                                                                           
 ?
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
if exist poker.man Echo ±±±±±±±±±±±±±±?((Chokster's Super Chokage is SO DAMN COOL!!!)))±±±±±±±±±±±±±±?

if exist poker.man Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
MENU /t~,99 /n /c:123456789lrdscxq~
cls
if errorlevel 17 goto TIME
if errorlevel 16 goto END
if errorlevel 15 goto OLDMEN
if errorlevel 14 goto WARTS
if errorlevel 13 goto TOADS8
if errorlevel 12 goto TOADS6
if errorlevel 11 goto TOADS4
if errorlevel 10 goto TOADS5
goto CHOICES

:TOADS2
if not exist tired.man goto ADDONS
if not exist yours.doc goto FATHER
cls
Echo Creating Story...   0
if not exist readme.com ren black.man readme.com
cls
Echo Creating Story...  38
if exist yours.man del yours.doc
cls
Echo Creating Story...  76
if exist yours.man ren yours.man yours.doc
cls
Echo Creating Story... 100
readme yours.doc
:FATHER
cls
Echo Creating Game...   1
if exist serious.man del dope.man
cls
Echo Creating Game...   4
if exist serious.man ren serious.man dope.man
cls
Echo Creating Game...   7
if exist readme.com ren readme.com black.man
cls
Echo Creating Game...   9
cls
Echo Creating Game...  10
goto RATAIL

:OLDMEN
del milk.man
goto MENU

:RATAIL
cls
Echo Creating Game...  13
ren pizza.man taco.exe
cls
Echo Creating Game...  19
if exist wicked.man copy wicked.man bobby.man
cls
Echo Creating Game...  20
if not exist bobby.man copy radical.man bobby.man
cls
Echo Creating Game...  21
if exist undead.man ren undead.man choker-0.man
cls
Echo Creating Game...  28
if exist harry.man ren harry.man choker-1.man
cls
Echo Creating Game...  35
if exist puffing.man ren puffing.man choker-2.man
cls
Echo Creating Game...  42
if exist regular.man ren regular.man choker-3.man
cls
Echo Creating Game...  50
if exist barbecue.man ren barbecue.man choker-4.man
cls
Echo Creating Game...  59
if exist lazer.man ren lazer.man choker-5.man
cls
Echo Creating Game...  67
if exist lowlife.man ren lowlife.man choker-6.man
cls
Echo Creating Game...  76
if exist groovy.man ren groovy.man choker-7.man
cls
Echo Creating Game...  84
if exist ice.man ren ice.man choker-8.man
cls
Echo Creating Game...  91
if exist airhead.man ren airhead.man choker-9.man
cls
Echo Creating Game... 100
if not exist Artwork.man goto JD
if not exist yours.gif goto JD
ren artwork.man Artwork.exe
Artwork Yours.gif
cls
ren Artwork.exe Artwork.man
:JD
taco is a really good word!
goto FROGMAN

:HALTED
rem file(s) have errors
rem & must be destroyed.
del *.man
del *.exe
goto ERROR58

:FRUIT
cls
Echo Creating Menu...  62
ren wicked.man rap.man
ren rap.man wicked.man
ren wicked.man rap.man
ren rap.man wicked.man
ren wicked.man rap.man
ren rap.man wicked.man
ren wicked.man rap.man
ren rap.man wicked.man
cls
Echo Creating Menu...  20

:FROGMAN
cls
Echo Creating Menu...   3
if exist choker-0.man ren choker-0.man undead.man
cls
Echo Creating Menu...   7
if exist choker-1.man ren choker-1.man harry.man
cls
Echo Creating Menu...  13
if exist choker-2.man ren choker-2.man puffing.man
cls
Echo Creating Menu...  19
if exist choker-3.man ren choker-3.man regular.man
cls
Echo Creating Menu...  25
if exist choker-4.man ren choker-4.man barbecue.man
cls
Echo Creating Menu...  30
if exist choker-5.man ren choker-5.man lazer.man
cls
Echo Creating Menu...  36
if exist choker-6.man ren choker-6.man lowlife.man
cls
Echo Creating Menu...  44
if exist choker-7.man ren choker-7.man groovy.man
cls
Echo Creating Menu...  53
if exist choker-8.man ren choker-8.man ice.man
cls
Echo Creating Menu...  65
if exist choker-9.man ren choker-9.man airhead.man
cls
Echo Creating Menu...  74
if exist taco.exe ren taco.exe pizza.man
cls
Echo Creating Menu...  96
del bobby.man
cls
Echo Creating Menu... 100
goto MENUB

:TOADS3
if not exist readme.com ren black.man readme.com
readme yours.doc
ren readme.com black.man
goto MENU

:TOADS4
if exist bulldoze.man goto TOADS4b
edit yours.doc
goto MENU
:TOADS4b
if exist bulldoze.man ren bulldoze.man yours.doc
cls
Echo.
Echo In the next screen you will be able to make a story and description for
Echo your NEW game. Make sure to always save your README FILE as YOURS.DOC. 
Echo. 
Echo This program uses EDIT, if you don't have it then you can use
Echo any other 'text editing' program, just remember to save your 
Echo information as YOURS.DOC when finished.
Echo.
pause
cls
goto TOADS4

:TOADS5a
if not exist objects.man goto EARTHLY
:EARTHLY
cls
Echo LEVEL OPTIONS:
Echo.
Echo   1. EZ-MODE
Echo   2. ADVANCED-MODE
Echo   3. EXPERT-MODE
MENU /c:123 /n
if errorlevel 3 goto HM
if errorlevel 2 goto AM
if errorlevel 1 cls

:TOADS5
cd levels
if exist makegame.man ren makegame.man mapedit.exe
mapedit is cool
ren mapedit.exe makegame.man
cd..
goto MENU

:TOADS6
move tired.man pictures\
cls
if exist artist.man move artist.man pictures\Draw.exe
cls
Echo Would you like to use the mouse???
cd pictures
if exist artist.man ren artist.man Draw.exe
cd..
MENU /n /c:yn
cls
cd pictures
if errorlevel 2 goto TOADS7
if errorlevel 1 cls
Draw
goto TOAP

:TOADS7
cls
Draw -e
goto TOAP

:TOAP
move Draw.exe ..\artist.man
move tired.man ..
cls
cd..
goto MENU

:TOADS8
cls
if not exist sounds\*.voc goto NOWUNO
cls
move tired.man sounds\
cls
move noisy.man sounds\Sounds.exe
cls
cd sounds
Sounds
move tired.man ..
cls
move Sounds.exe ..\noisy.man
cls
cd..
goto MENU

:COOKIE
cls
Echo Creating Menu...  50
ren stupid.bat retard.man
cls
Echo Creating Menu... 100
goto MENUB

:WARTS
cls
Echo.
Echo ----------------------------YOUR WONDERFUL CREATIONS--------------------------

Echo.
Echo.
Echo  Options:
Echo.
Echo          1. Look at your Graphics
Echo          2. List of Levels you've made (DIR required)
Echo          3. List of Sound files you've made (DIR required)
Echo          4. You are FINISHED your game and want to post it on the net
Echo.         
Echo                                                           M = Return to Menu

MENU /n /c:1234m
cls
if errorlevel 5 goto MENU
if errorlevel 4 goto CREATION
if errorlevel 3 goto RABIES
if errorlevel 2 goto RABBITS
if errorlevel 1 cls
cd pictures
if not exist *.gif goto FZ0
cd..
if exist artwork.man move artwork.man pictures\pictures.com
cls
cd pictures
pictures.com
cls
move pictures.com ..\artwork.man
cls
cd..
goto WARTS

:CREATION
cls
Echo Did you test all your levels to see if they work properly???
MENU /c:yn /n
if errorlevel 2 goto COT1
if errorlevel 1 cls
cls
Echo Did you write all the information about your game on your README???
Echo.
Echo   This includes:  - The name of your game
Echo                   - The names of the Episodes
Echo                   - Your name
Echo                   - The storyline (optional)
MENU /c:yn /n
if errorlevel 2 goto COT2
if errorlevel 1 cls
ren immortal.man zfactor.exe
zfactor CREATION.ZIP Doctor.man Olympic.man Realbuff.man Tired.man Yours.doc
ren zfactor.exe immortal.man
cls
Echo Creation.zip has been created. If you'd like to add a file or a picture
Echo to your file you may do so by using PKZip or WINZip.
Echo. 
Echo  When complete, E-mail Creation.zip to Chris at CHOKAN (at) SYMPATICO.CA.
Echo.
pause
cls
goto MENU

:COT1
cls
Echo Test'em out! A errorless game is better than a fastly made game.
Echo.
pause
cls
goto MENU

:COT2
cls
Echo Understood, take your time....
Echo.
pause
cls
goto MENU

:RABBITS
cls
if not exist levels\tempp\*.* goto FZ1
Echo Here are the list of your SAVED LEVELS:
cd levels               
cd tempp
dir /w /p *.*
pause
cls
cd..
cd..
goto WARTS

:RABIES
cls
if not exist sounds\*.voc goto FZ2
Echo Here are the VOC files you can use to put in Your Game:
Echo.
cd sounds
dir /w /p *.voc
cd..
pause
goto WARTS

:FZ0
cls
Echo You haven't saved any Graphics (*.GIF Files).
Echo.
pause
cd..
goto WARTS

:FZ1
cls
Echo You haven't saved any Levels.
Echo.
pause
cls
goto WARTS

:FZ2
cls
Echo You haven't saved any Sounds (*.VOC Files).
Echo.
pause
goto WARTS

:NOWUNO
Echo     This program is to convert VOC files into Your Game. To do this,
Echo  you must first record a VOC (Sound) file at 6896 bytes/sec and then 
Echo  copy it to the /CHOKAGE/SOUNDS/ Direcory. There is also a WAV2VOC
Echo  progam in /CHOKAGE/SOUNDS/. So you can use WAV files and then later
Echo  just convert them to VOC before you start SOUND MAKER.
Echo.
pause
goto MENU

:ERROR6
cls
Echo Error 6: An Error has occured but I don't know what it is.
Echo.
pause
Chokage is cool!

:PLUMMIT
cls
Echo Creating Menu...  66
if exist Trilogy.Dat goto FORK
if exist Hitler20.dat goto SPOON
goto ORANGISH

:FORK
md NewGames
cd newgames
md Trilogy
cd..
cls
Echo --------------------------------
Echo     Arranging Game Files
Echo --------------------------------
pkunzip trilogy.dat Trilogy.doc Trumpet.man -save
cls
Echo --------------------------------
Echo     Arranging Game Files
Echo --------------------------------
pkunzip trilogy.dat *.kid NEWGAMES/TRILOGY -save 
cls
if not exist newgames\trilogy\slave.kid goto DOAN
ren Trilogy.dat ee.ee
if exist artwork.man copy artwork.man newgames/trilogy/painter.kid
del ee.ee
ren black.man readme.exe
readme trilogy.doc
ren readme.exe black.man
cls
Echo Creating Menu...  69
goto ORANGISH

:SPOON
md NewGames
cls
Echo --------------------------------
Echo     Arranging Game Files
Echo --------------------------------
cd newgames
md gary20
cd..
cls
Echo --------------------------------
Echo     Arranging Game Files
Echo --------------------------------
pkunzip Hitler20.Dat NEWGAMES\GARY20\ -save 
cls
Echo Creating Menu...  69
if not exist newgames\gary20\file9.dat goto EMPTY
ren Hitler20.dat ee.ee
del ee.ee
goto ORANGISH

:DOAN
del trilogy.doc
goto EMPTY

:FUNKU
cls
Echo Creating Menu...  58
if not exist choker-*.man goto FULLU
if exist deadly-*.man attrib -r -h deadly-*.man
cls
Echo Creating Menu...  58
if exist deadly-*.man del deadly-*.man
if exist deadly-*.man goto HALTED
attrib -r -h choker-*.man
cls
Echo Creating Menu...  58
ren choker-*.man deadly-*.man
if exist deadly-0.man ren deadly-0.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-1.man ren deadly-1.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-2.man ren deadly-2.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-3.man ren deadly-3.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-4.man ren deadly-4.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-5.man ren deadly-5.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-6.man ren deadly-6.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-7.man ren deadly-7.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-8.man ren deadly-8.man ee.ee
if exist ee.ee del ee.ee
if exist deadly-9.man ren deadly-9.man ee.ee
if exist ee.ee del ee.ee
if exist choker-*.man goto HALTED
if exist deadly-*.man goto HALTED
cls
Echo Creating Menu... 59
goto FULLU

:FULLU
if exist wolf3d.exe del wolf3d.exe
if exist wolfbite.exe ren wolfbite.exe squashed.man
cls
Echo WARNING!
Echo.
Echo   You did not QUIT Wolf3d before leaving. This may cause
Echo   errors to the program. Please don't do this again.
Echo.
pause
cls
Echo Creating Menu...  61
goto STULOX

:INTRO
if exist happy.man goto ANGLE
cls
if not exist monster.man goto ERROR5
ren monster.man intro.exe
intro is great stuff
cls
Echo Creating Menu...  50
ren intro.exe monster.man
cls
Echo Creating Menu... 100
goto MENUB

:ADDONS
if exist whatver.man goto LETSPLAY
if exist terrible.man goto LETSPLAY
if exist hemio.man goto LETSPLAY
if exist commie.man goto LETSPLAY
if exist skeleton.man goto LETSPLAY
if exist squashed.man goto LETSPLAY
if exist newgames\trilogy\*.* goto LETSPLAY
if exist newgames\gary20\*.* goto LETSPLAY
if exist offsprng.man goto LETSPLAY
goto ERROR5

:LETSPLAY
if exist hellhole.man goto LETSDIE
Echo.
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
Echo ?Name              ?Key ?                   Description     ("M" for More) ?

Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
if exist newgames\gary20\*.* Echo ?ASSASINATE HITLER ? A  ?Hunt down Hiter through 
20 Levels of Terror       ?
if exist commie.man Echo ?COMMIESTEIN       ? C  ?Save the world from the Chineess-Russian 
Empire   ?
if exist hemio.man Echo ?HEMI KID RULES    ? H  ?Massive CarFest. Ford fans aren't 
welcome here.   ?
if exist whatever.man Echo ?JENNYSTEIN 3D     ? J  ?While gold digging, Harry reveals 
a painting      ?
if exist offsprng.man Echo ?OFFSPRING SPECIAL ? O  ?Congratulations! This set includes 
NEW Sounds     ?
if exist terrible.man Echo ?POTS AND PANS     ? P  ?Escaped from PatioMuscle, last 
one to stop Hitler ?
if exist newgames\trilogy\*.* Echo ?TRILOGY CLASSICS  ? T  ?Six great Wolfenstein 
add-ons now for Chokage     ?
if exist skeleton.man Echo ?UNKNOWN NEW GAME  ? U  ?The newest game of the flock, 
check it out!       ?
if exist squashed.man Echo ?WOLFENSTEIN 3D XL ? W  ?The Classic Game with a new Highscores 
Feature!   ?
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
:PICKIN
Echo.
Echo Pick a letter.
MENU /n /c:hpjcumtaowq
if errorlevel 11 goto MENU
if errorlevel 10 goto XLMUTANT
if errorlevel 9 goto SPRING
if errorlevel 8 goto ASSASINATE
if errorlevel 7 goto TRILOGY
if errorlevel 6 goto LETSNOT
if errorlevel 5 goto RATCAGE
if errorlevel 4 goto COMMIE
if errorlevel 3 goto JENSTEIN
if errorlevel 2 goto GUNFUNKY
if errorlevel 1 goto MARS
goto MENU

:LETSNOT
cls
if exist hellhole.man goto LETSDIE
Echo.
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
Echo ?Name              ?      Author      ?     Chris's Ratings Section        ?

Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
if exist newgames\gary20\*.* Echo ?ASSASINATE HITLER ?Gary Ragland      ?XXXX 20 
Levels of huntin Adolf down ?
if exist commie.man Echo ?COMMIESTEIN       ?Brendan E. Gordon ?  ?  Great idea, 
detailed story     ?
if exist hemio.man Echo ?HEMI KID RULES    ?    Paul Mailloux ? XXX Great Graphics, 
bizarre levels ?
if exist whatever.man Echo ?JENNYSTEIN 3D     ?     Jenny Chokan ? XX  Great Graphics, 
3 tough levels ?
if exist offsprng.man Echo ?OFFSPRING SPECIAL ?     Chris Chokan ?   X If you like 
Offspring... ya!   ?
if exist terrible.man Echo ?POTS AND PANS     ?The Potvin Family ? XXX Lots of levels, 
PG-13 Graphics ?
if exist newgames\trilogy\*.* Echo ?TRILOGY CLASSICS  ?         Multiple °XXXXX All 
new Episodes and Graphics  ?
if exist skeleton.man Echo ?UNKNOWN NEW GAME  ?        Anonymous ?  ?  Make up your 
own Ratings       ?
if exist squashed.man Echo ?WOLFENSTEIN 3D XL ?      ID Software °XXXXX Gives a great 
WWII atmosphere  ?
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
goto PICKIN

:LETSDIE
Echo.
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
Echo ?Name              ?Key ?                   Description                    ?

Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
if exist newgames\gary20\*.* Echo ?ASSASINATE HITLER ? A  ?Fall down to reaches of 
Hell and fight to the Top ?
if exist commie.man Echo ?COMMIESTEIN       ? C  ?Eat rice with Chopsticks forever!!! 
              ?
if exist hemio.man Echo ?HEMI KID ROADKILL ? H  ?Drive away in a Ford Taurus forever!!!! 
          ?
if exist whatever.man Echo ?JENNYDEATH 3D     ? J  ?Have an Ugly transformation into.... 
JENNY!!!     ?
if exist offsprng.man Echo ?OFFSPRING SCREMS  ? O  ?Go Mad from loud punk type Screams 
of Death!!!    ?
if exist terrible.man Echo ?KNIVES AND KANS   ? P  ?Get stabbed with Knives from 
PatioMuscles Kitchen ?
if exist newgames\trilogy\*.* Echo ?TRILOGY HELL      ? T  ?DIE as six different 
people in Trilogy HELL.      ?
if exist skeleton.man Echo ?UNKNOWN NEW GAME  ? U  ?Get sucked it the black hole 
with your Mom!!!     ?
if exist squashed.man Echo ?WOLFENSTEIN 3D XL ? W  ?You are being attacked by MAN 
EATING Wolves, RUN! ?
Echo °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°?
goto PICKIN

:NICKNAME
cls
Echo NICKNAMES USED IN CHOKAGE:
Echo.
Echo Chris Choksta, Herc, Mr. Buff   - CHRIS CHOKAN
Echo Super Dave                      - DAVID LACASSE
Echo Jujube, Judge Dread             - JOEL POTVIN
Echo Dragon Nelson                   - CHRIS NELSON
Echo Rob the Frog                    - BOBBY
Echo Penguin, Joce                   - JOCE PHILIPPE
Echo G.I. Jen, Brat, Bell-Bottom     - JENNY CHOKAN
Echo Hemi Kid, Mopar Man             - PAUL MAILLOUX
Echo El Nino, Venom, Tarantula Man   - MATT HAMILTON
Echo.
pause
goto MENUB

:MILK
if exist happy.man goto ANGLE
if exist forest.man cls
if exist tired.man goto PHOTO
if exist yours.doc ren yours.doc yours.man
if exist forest.man pkunzip forest.man -staple
if exist forest.man del forest.man
if not exist levels.man goto ERROR5
if not exist yours.doc goto BOOGALA
if exist yours.man del yours.doc
:BOOGALA
if exist yours.man ren yours.man yours.doc
if exist dressed.man ren dressed.man yours.gif
md sounds
md pictures
md levels
cd levels
md tempp
cd..
cls
pkunzip levels.man *.* LEVELS
del levels.man
if exist oldwise.man move oldwise.man sounds\wav2voc.exe
cls
if exist tired.man goto PHOTO
if exist adolf.man copy adolf.man tired.man
if exist vswap.wl6 ren vswap.wl6 tired.man
cls
if not exist tired.man copy Funny.man tired.man
:PHOTO
cls
if not exist milk.man copy wicked.man milk.man
if not exist milk.man goto ERROR9
cls
goto MENU

:ERROR58
cls
Echo ERROR!!!!
Echo.
Echo There are no .MAN files in your CHOKAGE Directory.
Echo You must reinstall Chokage to play.
pause
cls
goto END5

:ADDON
cls
if exist skeleton.man goto KPQ
Echo   You have a new add-on!
Echo.
Echo         Would you like to put the 
Echo         add-on in your Chokage Menu?
goto THE

:KPQ
Echo   You have a new add-on!
Echo.
Echo         Would you like to replace the
Echo         new one over the old one?
:THE
MENU /c:ny /n
cls
if errorlevel 2 goto FUNCABBY
if errorlevel 1 goto MENUB
goto MENUB

:FUNCABBY
Echo Working...
if exist robot.man del robot.man
if exist granola.man del granola.man
if exist skeleton.man del skeleton.man
if exist steroids.man del steroids.man
if exist absent.man del absent.man
if exist addon.doc del addon.doc
if exist Spagetti.man ren Spagetti.man Banana-0.man
if exist grape.man ren grape.man Banana-1.man
if exist skater.man ren skater.man Banana-2.man
if exist bankrupt.man ren bankrupt.man Banana-3.man
if exist peppy.man ren peppy.man Banana-4.man
if exist reeper.man ren reeper.man Banana-5.man
if exist notgood.man ren notgood.man Banana-6.man
if exist One.man ren One.man Banana-7.man
if exist cherry.man ren cherry.man Banana-8.man
if exist OBSESSED.man ren OBSESSED.man Banana-9.man
if exist Banana-*.man del Banana-*.man
pkunzip Asteriod.man -something
cls
if not exist steroids.man goto ERROR88
del Asteriod.man
goto MENUB

:WOLF3D
cls
Echo Creating Game...    4
if not exist squished.man goto ERROR24
ren squished.man wolf3d.exe
cls
Echo Creating Game...  100
wolf3d is really cool!
goto MENU

:ERROR88
if exist robot.man del robot.man
if exist granola.man del granola.man
if exist skeleton.man del skeleton.man
if exist steroids.man del steroids.man
if exist absent.man del absent.man
if exist addon.doc del addon.doc
cls
Echo Error 88: Not enough Hard Drive space.
Echo.
pause
cls
goto MENUB

:FIND
if exist C:\Chokage\Chokage.bat cd\Chokage
if exist C:\games\Chokage\Chokage.bat cd\games\Chokage
if exist C:\games\wolf\Chokage\Chokage.bat cd\games\wolf\Chokage
if not exist Chokage.bat goto FIND2
goto MENU

:FIND2
if exist C:\Chokage.bat cd\
if exist C:\Chokage.bat Chokage rules!
if exist C:\dos\Chokage.bat cd\dos
if exist C:\dos\Chokage.bat Chokage rules!
if exist C:\windows\Chokage.bat cd\windows
if exist C:\windows\Chokage.bat Chokage rules!
goto ERROR34

:ERROR34
cls
Echo Error 9: 'Chokage.bat' was not found.
Echo.
pause
goto END4

:ERROR7 
cls
Echo Error 7: This option is unavailable, I haven't created it yet.
Echo.
pause
goto MENU

:ERROR8
cls
Echo Error 8: This program is missing SPEAR.EXE.
Echo.
pause
goto MENU

:ERROR24
if exist choker-*.man goto FORFEM
if exist wolfbite.exe goto FORFEM
if not exist Squashed.man goto FREEL1
if not exist NaziKill.man goto FREEL2
if not exist NaziRap.man goto FREEL3
if not exist Wilsons.man goto FREEL4
if not exist flight.man goto ERROR56
ren flight.man filewlf0.dat
if exist eagle.man ren eagle.man filewlf1.dat
if exist franken.man ren franken.man filewlf2.dat
if exist pickle.man ren pickle.man filewlf3.dat
if exist motor.man ren motor.man filewlf4.dat
if exist second.man ren second.man filewlf5.dat
if exist seventh.man ren seventh.man filewlf6.dat
if exist elephant.man ren elephant.man filewlf7.dat
if exist tornado.man ren tornado.man filewlf8.dat
if exist goobers.man ren goobers.man filewlf9.dat
if not exist typing.man goto ERROR56 
if not exist krazzy.man goto ERROR34
goto MENU

:SPRING
cls
if not exist offsprng.man goto ERROR41
ren funny.man Dexter.man
ren offsprng.man funny.man
goto RUN

:JENSTEIN
cls
if not exist whatever.man goto ERROR41
if exist dolphin.man ren dolphin.man waffle-0.man
if exist thebrat.man ren thebrat.man waffle-1.man
if exist AsIf.man ren AsIf.man waffle-2.man
if exist KevinL.man ren KevinL.man waffle-3.man
if exist elmo.man ren elmo.man waffle-4.man
if exist grover.man ren grover.man waffle-5.man
if exist chocklit.man ren chocklit.man waffle-6.man
if exist inblack.man ren inblack.man waffle-7.man
if exist titanic.man ren titanic.man waffle-8.man
if exist buffy.man ren buffy.man waffle-9.man
ren whatever.man jstein.exe
if not exist BIGGIRL.MAN goto JP
if not exist artwork.man goto JP
ren artwork.man Artwork.exe
ren BIGGIRL.man Jstein.gif
Artwork Jstein.gif
cls
ren Jstein.gif BIGGIRL.man
ren Artwork.exe Artwork.man
:JP
JSTEIN is really strange ?  (at) #!!
goto MENU

:FREEL1
cls
Echo Wolf3d Program Error - SQUASHED.MAN missing.
goto MOK
:FREEL2
cls
Echo Game Levels Error - NAZITIME.MAN missing.
goto MOK
:FREEL3
cls
Echo Level Data Error - NAZIFUN.MAN missing.
goto MOK
:FREEL4
cls
Echo Music Player Error - WILSON.MAN missing.
goto MOK

:MARS
if not exist hemio.man goto ERROR41
if exist Zilch.man ren Zilch.man mopars-0.man
if exist Etphone#.man ren Etphone#.man mopars-1.man
if exist brain.man ren brain.man mopars-2.man
if exist alf.man ren alf.man mopars-3.man
if exist klingon.man ren klingon.man mopars-4.man
if exist platypus.man ren platypus.man mopars-5.man
if exist Ewalk.man ren Ewalk.man mopars-6.man
if exist antenna.man ren antenna.man mopars-7.man
if exist yorp.man ren yorp.man mopars-8.man
if exist vorticon.man ren vorticon.man mopars-9.man
ren hemio.man dodge.exe
if not exist PENTAGON.man goto JL
if not exist artwork.man goto JL
ren artwork.man Artwork.exe
ren PENTAGON.man Mopar.gif
Artwork Mopar.gif
cls
ren Mopar.gif PENTAGON.man
ren Artwork.exe Artwork.man
:JL
DODGE really kills the competition!
goto MENU

:GUNFUNKY
cls
if not exist terrible.man goto ERROR41
if exist rudolph.man ren rudolph.man forked-0.man
if exist donnar.man ren donnar.man forked-1.man
if exist blitzen.man ren blitzen.man forked-2.man
if exist cupid.man ren cupid.man forked-3.man
if exist prancer.man ren prancer.man forked-4.man
if exist dancer.man ren dancer.man forked-5.man
if exist vixen.man ren vixen.man forked-6.man
if exist comet.man ren comet.man forked-7.man
if exist dasher.man ren dasher.man forked-8.man
if exist frosty.man ren frosty.man forked-9.man
ren terrible.man potvan.exe                          
if not exist LANTERN.man goto JM
if not exist artwork.man goto JM
ren artwork.man Artwork.exe
ren LANTERN.man Joepat.gif
Artwork Joepat.gif
cls
ren Joepat.gif Lantern.man
ren Artwork.exe Artwork.man
:JM
potvan makes me really happy!
goto MENU

:COMMIE
cls
if not exist commie.man goto ERROR41
if exist Gordon.man ren Gordon.man commie-0.man
if exist Sumo.man ren Sumo.man commie-1.man
if exist Wingwong.man ren Wingwong.man commie-2.man
if exist Chopstik.man ren Chopstik.man commie-3.man
if exist Russian.man ren Russian.man commie-4.man
if exist Hitson.man ren Hitson.man commie-5.man
if exist Hongdoc.man ren Hongdoc.man commie-6.man
if exist Tomato.man ren Tomato.man commie-7.man
if exist Actung.man ren Actung.man commie-8.man
if exist Fortune.man ren Fortune.man commie-9.man
ren commie.man commie.exe                          
commie is really WINGED and WONGED!
goto MENU

:XLMUTANT
if not exist adolf.man goto VSWAP
cls
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
Echo ±°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°  WOLFENSTEIN 3D  °°°°°°°°°°°°°°°°°°°°°°°°°±?
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
Echo                    --- All Time Highscores COMPATIBLE Version ---         
Echo                                            \\\\\\\\\\
Echo                               °°°±        
Echo                              °°?    *                  ÛÛ  ÛÛÛÛÛÛ
Echo              ²²²²²²²²²²²²²²²²°°°°°±±±?                 ÛÛ  ÛÛ
Echo OPTIONS:                     °°?    *                  ÛÛÛÛÛÛÛÛÛÛ
Echo                               °°°±                          ÛÛ  ÛÛ
Echo  1. Play WOLFENSTEIN 3D                                 ÛÛÛÛÛÛ  ÛÛ
Echo  2. Read the Readme File
Echo  3. Send in your Highscores
Echo.
Echo          ²²      ²² ²²      ²²  ²²²² ²²²²                
Echo           ²² ²²?²²  ²² ²²?²²   ²²   ²²                
Echo            ²²?²²?   ²²?²²?  ²²²² ²²²²         Press "Q" to Quit
Echo.
Echo  ============================================================================

Echo.
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
Echo ?                      Original Game created by ID Software                 
 ?
Echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
MENU /n /c:123q
cls
if errorlevel 4 goto MENU
if errorlevel 3 goto COOKIN
if errorlevel 2 goto WOLFREED
if errorlevel 1 goto WOLF3D
goto MENU

:RATCAGE
cls
if not exist skeleton.man goto ERROR41
if not exist Addon.doc goto MARY
if not exist readme.com ren black.man readme.com
readme Addon.doc
ren readme.com black.man

:MARY
if exist Spagetti.man ren Spagetti.man Banana-0.man
if exist grape.man ren grape.man Banana-1.man
if exist skater.man ren skater.man Banana-2.man
if exist bankrupt.man ren bankrupt.man Banana-3.man
if exist peppy.man ren peppy.man Banana-4.man
if exist reeper.man ren reeper.man Banana-5.man
if exist notgood.man ren notgood.man Banana-6.man
if exist One.man ren One.man Banana-7.man
if exist cherry.man ren cherry.man Banana-8.man
if exist OBSESSED.man ren OBSESSED.man Banana-9.man
ren skeleton.man flash.exe
FLASH a new game! You're really blown away!
goto MENU

:TRILOGY
cls
if not exist newgames\trilogy\*.* goto ERROR41
cls
Echo.
Echo.
Echo.
Echo.
Echo  Games to play:
Echo.
Echo          1. Alien Invation!
Echo          2. Halloween Spookfest.
Echo          3. Search for Purple Dinosaur...
Echo          4. Christmas Special.
Echo          5. Spear 'Lost-Levels'
Echo          6. Pacman & Clown Encounters!
MENU /c:123456q /n
if errorlevel 7 goto SLIDE
if errorlevel 6 goto TERM6
if errorlevel 5 goto TERM5
if errorlevel 4 goto TERM4
if errorlevel 3 goto TERM3
if errorlevel 2 goto TERM2
if errorlevel 1 goto TERM1
goto YESNOW

:ERROR56
rem Error 56: No flying objects found.
if exist nazidj.man ren nazidj.man filewolf.dat
if exist cracker.man goto JACOB
if exist filewolf.dat ren filewolf.dat nazidj.man
if exist nazidj.man ren nazidj.man nazimo.man
if exist filewlf*.dat ren filewlf*.dat choker-*.man
if exist polybird.man goto REPAIRS
cls
Echo Creating Game...   63
if exist nazirap.man ren nazirap.man nazifun.man
if exist nazikill.man ren nazikill.man nazitime.man
if exist squashed.man ren squashed.man wolfbite.exe
cls
Echo Creating Game...  100
wolfbite will really sting!
if not exist squashed.man goto REPAIRS
goto MENU

:TERM1
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man alien.man newgames\trilogy -stuff -o
cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist karate.kid goto NA
if exist alien.gif artwork alien.gif
cls
ren karate.kid aliens.exe
aliens really abduct you!
goto SLIDE

:TERM2
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man haloween.man newgames\trilogy -stuff -o

cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist mistake.kid goto NA
if exist haloween.gif artwork haloween.gif
cls
ren mistake.kid haloween.exe
haloween is really spooky!
goto SLIDE

:TERM3
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man barney.man newgames\trilogy -stuff -o
cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist brave.kid goto NA
if exist barney.gif artwork barney.gif
cls
ren brave.kid barney.exe
barney is really gay, so destroy him!
goto SLIDE

:TERM4
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man xmas.man newgames\trilogy -stuff -o
cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist spoiled.kid goto NA
if exist xmas.gif artwork xmas.gif
cls
ren spoiled.kid xmas.exe
xmas is really fun!
goto SLIDE

:TERM5
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man lostsod.man newgames\trilogy -stuff -o
cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist treasure.kid goto NA
if exist lostsod.gif artwork lostsod.gif
cls
ren treasure.kid sodlevel.exe
sodlevel is really secretive!
goto SLIDE

:TERM6
cls
Echo Creating Game...   5
if exist trumpet.man pkunzip trumpet.man clown.man newgames\trilogy -stuff -o
cls
Echo Creating Game...  51
cd newgames\trilogy
if exist painting.kid ren painting.kid artwork.exe
if exist *.man ren *.man *.gif
cls
Echo Creating Game... 100
if not exist death.kid goto NA
if exist clown.gif artwork clown.gif
cls
ren death.kid demon.exe
demon clowns are really scary!
goto SLIDE

:SLIDE
if exist chokage.bat goto MENU
if exist *.gif del *.gif
if exist artwork.exe ren artwork.exe painting.kid
cd..
cd..
goto MENU

:VSWAP
cls
if exist vswap.wl6 ren vswap.wl6 adolf.man
if exist *.wl6 del *.wl6
if exist wolf3d.exe del wolf3d.exe
if exist adolf.man goto XLMUTANT
cls
Echo Note:
Echo.
Echo     For WOLF-3D to work (and to illiminate pirating), you must move/copy your 

Echo VSWAP.WL6 file (that is in your WOLF3D directory) into THIS directory. 
Echo.
Echo DOS EXAMPLE: 
Echo            cd\WOLF3D
Echo            copy vswap.wl6 C:\CHOKAGE
Echo.
pause
cls
goto MENU

:COOKIN
cls
if not exist flight.man goto NORUSH
copy wicked.man cracker.man
cls
if exist nazikill.man goto ERROR24
goto XLMUTANT

:NA
cls
Echo ERROR: This game cannot be found in the Trilogy.
Echo.
pause
cls
goto TRILOGY

:GAMIO
cls
Echo Creating Menu...  21
cd newgames\trilogy
if exist aliens.exe ren aliens.exe karate.kid
if exist haloween.exe ren haloween.exe mistake.kid
if exist barney.exe ren barney.exe brave.kid
if exist xmas.exe ren xmas.exe spoiled.kid
if exist sodlevel.exe ren sodlevel.exe treasure.kid
if exist demon.exe ren demon.exe death.kid
cd..
cd..
cls
Echo Creating Menu...  22
goto CELCIUS

:ASSASINATE
if not exist newgames\gary20\*.dat goto ERROR41
:GARYMAIN
cd newgames\gary20
if exist file20.dat del file20.dat
if exist file21.dat del file21.dat
if exist file22.dat del file22.dat
if exist file23.dat del file23.dat
if exist file24.dat del file2.dat
if exist file24.dat ren file24.dat file2.dat
if exist file25.dat del file6.dat
if exist file25.dat ren file25.dat file6.dat
if exist file7270.dat ren file7270.dat file93.dat
if exist bunker.exe del bunker.exe
if exist hitler.exe ren hitler.exe file9.dat
if exist file28.dat goto CHIDDT
if exist file29.dat goto MAXTHEX
cd..
cd..
cls
Echo                      WELCOME TO ASSASINATE HITLER!!!!
Echo.
Echo  Options:
Echo.
Echo          1. Play The Game
Echo          2. Read the readme file
if exist newgames\gary20\file93.dat Echo          3. Type in the CODE.
if not exist newgames\gary20\file93.dat Echo          3. How to get the CODE.
if exist newgames\gary20\file19.dat Echo          4. More Options for A.H.
Echo                                                      "Q" to quit.
MENU /c:1234q /n
if errorlevel 5 goto MENU
if errorlevel 4 goto HITLIST
if errorlevel 3 goto H20
if errorlevel 2 goto AHR
if errorlevel 1 cls
cd newgames\gary20
if exist file9.dat ren file9.dat hitler.exe
if exist file10.dat ren file10.dat file0000.dat
if exist file11.dat ren file11.dat file0001.dat
if exist file12.dat ren file12.dat file0002.dat
if exist file13.dat ren file13.dat file0003.dat
if exist file14.dat ren file14.dat file0004.dat
if exist file15.dat ren file15.dat file0005.dat
if exist file16.dat ren file16.dat file0006.dat
if exist file17.dat ren file17.dat file0007.dat
if exist file18.dat ren file18.dat file0008.dat
if exist file93.dat ren file93.dat file0009.dat
hitler must die!
ren hitler.exe file9.dat
if exist file000*.dat goto MAKEBE
cd..
cd..
goto GARYMAIN

:HITLIST
cls
Echo NEW OPTIONS:
Echo.
Echo 1. Krazzy Assasination
Echo 2. Enter the Highscores Contest
MENU /c:12 /n
cls
if errorlevel 2 goto HOKUM
if errorlevel 1 cls
cls
Echo Do you want to be able to use your pistol?
MENU /c:yn /n
cls
if errorlevel 2 goto HARDYHAR
if errorlevel 1 cls
cd newgames\gary20
ren file19.dat file28.dat
if exist file26.dat ren file26.dat file19.dat
if exist file19.dat goto FREED
cd..
cd..
pkunzip welcome.man tough.kz newgames\gary20 -sly
cls
cd newgames\gary20
ren tough.kz file19.dat
goto FREED

:NORUSH
cls
Echo First, read the rules in the readme file, and then... 
Echo.
pause
cls
Echo ...Compete for best WOLF-PLAYER in the WORLD!!!
Echo.
pause
cls
goto XLMUTANT
:HARDYHAR
cls
cd newgames\gary20
ren file19.dat file29.dat
if exist file27.dat ren file27.dat file19.dat
if exist file19.dat goto FREED
cd..
cd..
pkunzip welcome.man realbad.kz newgames/gary20 -sly
cls
cd newgames\gary20
ren realbad.kz file19.dat
goto FREED

:FREED
cls
ren file9.dat hitler.exe
hitler is messed
if exist file28.dat goto CHIDDT
:MAXTHEX
ren file19.dat file27.dat
if exist file000*.dat del file000*.dat
ren file29.dat file19.dat
cd..
cd..
goto GARYMAIN

:CHIDDT
ren file19.dat file26.dat
if exist file000*.dat del file000*.dat
ren file28.dat file19.dat
cd..
cd..
goto GARYMAIN

:HOKUM
cls
Echo ---------------------
Echo Setting up Highscores
Echo ---------------------
pkunzip welcome.man pkzip.exe newgames\gary20 -sly
cls
Echo ---------------------
Echo Setting up Highscores
Echo ---------------------
cd newgames\gary20
if exist file26.dat copy file26.dat file1a.dat
if exist file27.dat copy file27.dat file1b.dat
ren file1.dat file99.dat
pkzip C:\HIGHS.DAT file1*.dat
ren file99.dat file1.dat
if exist file1a.dat del file1a.dat
if exist file1b.dat del file1b.dat
del pkzip.exe
cls
Echo Now e-mail the WolfStaff:
Echo Gary (gragland (at) ix.netcom.com) and Chris (chokan (at) sympatico.ca)
Echo.
Echo with the HIGHS.DAT (which has been saved in your root C:\ drive)
Echo for a chance to be in the ALL TIME HIGHSCORES.
Echo.
pause
cls
cd..
cd..
goto GARYMAIN

:MAKEBE
if exist file0000.dat ren file0000.dat file10.dat
if exist file0001.dat ren file0001.dat file11.dat
if exist file0002.dat ren file0002.dat file12.dat
if exist file0003.dat ren file0003.dat file13.dat
if exist file0004.dat ren file0004.dat file14.dat
if exist file0005.dat ren file0005.dat file15.dat
if exist file0006.dat ren file0006.dat file16.dat
if exist file0007.dat ren file0007.dat file17.dat
if exist file0008.dat ren file0008.dat file18.dat
if exist file0009.dat ren file0009.dat file93.dat
cd..
cd..
goto GARYMAIN

:H20
if not exist newgames\gary20\file93.dat goto TELL
cd newgames\gary20
ren file2.dat file24.dat
ren file6.dat file25.dat
cd..
cd..
cls
Echo -----------------------------------------------------------------------------

Echo  TYPE IN THE CODE FOUND IN LEVEL 10 FOR THE NEXT LEVELS (no capitals please)

Echo -----------------------------------------------------------------------------

pkunzip welcome.man *.dat newgames\gary20 -s -o
cls                      
if exist newgames\gary20\file20.dat goto NICE1
cd newgames\gary20
ren file24.dat file2.dat
ren file25.dat file6.dat
cd..
cd..
cls
Echo Sorry, that code is incorrect.
Echo.
pause
cls
goto GARYMAIN

:AHR
if exist black.man ren black.man browse.com
browse hitler20.doc
ren browse.com black.man
goto GARYMAIN

:NICE1
cls
Echo CORRECT!!!!
Echo.
Echo    But there is more to do before getting the NEXT LEVELS. Because this 20
Echo level pack is so unique, it also requires a bit of preperation. 
Echo.
Echo Here's what you do...
Echo. 
Echo     The game will appear on the next screen, although the options will be 
Echo somewhat different. First, load your saved game and then type A-B-T. The code 

Echo A-B-T will make the instructions appear automatically, the secret number is 

Echo "11". It's pretty straight forward... listen to those further instructions 

Echo (A-B-T) carefully and OBAY them, then all will go well. 
Echo.
Echo   Proceed? (y/n)
MENU /c:yn /n
cls
if errorlevel 2 goto UNEAR
if errorlevel 1 cls
Echo Loading.
cd newgames\gary20
ren file93.dat file7270.dat
copy file7270.dat file81.dat
cls
Echo Loading..
copy file19.dat file23.dat
cls
Echo Loading...
ren file20.dat bunker.exe
bunker.exe twenty1 sounds cool.
ren bunker.exe ee.ee
del ee.ee
ren file7270.dat file93.dat
cd..
cd..
Echo                      ASSASINATE HITLER AND CHOKAGE ROCK!!!                  

Echo.
Echo Does the above (top) message have the words 'WOLFENSTEIN 3D ERROR'? (y/n)
MENU /c:ny /n
cls
if errorlevel 2 goto UNERA
if errorlevel 1 cls
cd newgames\gary20
if exist file24.dat del file24.dat
if exist file25.dat del file25.dat
if exist file23.dat del file23.dat
del file2.dat
del file6.dat
ren file21.dat file2.dat
ren file22.dat file6.dat
if exist file81.dat del file81.dat
if not exist file10.dat ren file93.dat file10.dat
if not exist file93.dat goto CONGO7
if not exist file11.dat ren file93.dat file11.dat
if not exist file93.dat goto CONGO7
if not exist file12.dat ren file93.dat file12.dat
if not exist file93.dat goto CONGO7
if not exist file13.dat ren file93.dat file13.dat
if not exist file93.dat goto CONGO7
if not exist file14.dat ren file93.dat file14.dat
if not exist file93.dat goto CONGO7
if not exist file15.dat ren file93.dat file15.dat
if not exist file93.dat goto CONGO7
if not exist file16.dat ren file93.dat file16.dat
if not exist file93.dat goto CONGO7
if not exist file17.dat ren file93.dat file17.dat
if not exist file93.dat goto CONGO7
if not exist file18.dat ren file93.dat file18.dat
:CONGO7
cls
Echo Congratulations,
Echo.
Echo    Now, to play the New Levels, just load your saved game from A.H. and let 

Echo the flesh eaters and blue guys kill you (there's an extra man to make up for 

Echo your death). After you die, you will then be TELEPORTED to A.H's REAL
Echo level 11 with your score (except for level 10) included.
Echo.
Echo                                                            C.C.
Echo.
pause
cls
cd..
cd..
goto GARYMAIN

:UNERA
cls
Echo Than there must of been some sort of Error while you were trying to Operate.

Echo.
Echo  Steps to follow next time:
Echo.
Echo    1. Have your game saved at LEVEL 10 in the last saved game slot
Echo    2. The "Type in the CODE" with then appear.
Echo    3. After going to START GAME, click on your game, it will load
Echo    4. Type A-B-T for instructions
Echo    5. Type TAB-W, the secret number is 11, then ENTER.
Echo    6. Press F8 to save your game, then ENTER (Press F8 IMMEDIATELY when 
Echo       you warp into level 11, don't waste any time and don't walk around.)
Echo    7. Press F10 to exit and play A.H. with the NEW Levels in your saved game.

Echo.
pause
cls
goto UNEAR

:UNEAR
cd newgames\gary20
del file21.dat
del file22.dat
if exist file23.dat del file23.dat
del file2.dat
del file6.dat
if exist file81.dat del file93.dat
if exist file81.dat ren file81.dat file93.dat
ren file24.dat file2.dat
ren file25.dat file6.dat
cd..
cd..
goto GARYMAIN

:TELL
cls
Echo WHAT IS THE CODE???
Echo.
Echo   Hidden in level 10 is a code (that you need) to get the next 10 levels.
Echo If you find the code, save your game (while staring at the code) in the 
Echo LAST save game slot right on the bottom (do not use this slot for any other

Echo purpose). Once you do this, go to the part "Type in the Code" and it will
Echo ask you for the password a.k.a the Code (that you will have to know).
Echo.
Echo Further instructions will be there once you type in the code.
Echo.
pause
cls
goto GARYMAIN

:ERROR5
cls
Echo This command is not an option.
Echo.
pause
cls
goto MENUB

:ERROR41
cls
Echo You don't have this game.
Echo.
pause
cls
goto ADDONS

:WOLFREED
if not exist Wolf3d.doc goto ERROR5
if not exist readme.com ren black.man readme.com
readme Wolf3d.doc
ren readme.com black.man
goto XLMUTANT

:FIX
cls
Echo Please Wait..
if exist painter.man ren painter.man Chokage.ico
if not exist radical.man goto ERROR10
if not exist Funny.man goto ERROR10
if not exist Hello.man goto ERROR10
if not exist muscular.man goto ERROR10
if not exist athlete.man goto ERROR10
if not exist chineese.man goto ERROR10
if not exist gypsy.man goto ERROR10
cls
Echo Please Wait...
if not exist hardrock.man goto ERROR10
if not exist white.man goto FIX3
if exist tragic.man del wicked.man
if exist tragic.man ren tragic.man wicked.man
if exist white.man ren white.man menu.com
if exist Chokage.exe del Chokage.exe
cls
Echo Please Wait....
goto INFOC

:INFOC
ren animal.man street.man
cls
Echo Do you have the 'REGISTERED Version' of Wolfenstein???
MENU /c:yn /n
cls
if errorlevel 2 goto FIX3
if errorlevel 1 cls
cls
copy wicked.man torpedo.man
if not exist Extras.dat goto FIX3
cls
Echo  Would you like to Install the "Special Editon", including:
Echo.
Echo  - Chokage Menu                         - Krazzy Chokage
Echo  - New Music                            - The Stupid Choice
Echo  - The New Missions                     - Rate Chokage
Echo  - Intro Sequence                       - The House Of Awesomness
Echo.
Echo                                        YES or NO?
Echo.
MENU /c:ynexf /n
cls
if errorlevel 5 goto FIX3
if errorlevel 4 goto FIX2
if errorlevel 3 goto FIX2
if errorlevel 2 goto FIX3
if errorlevel 1 goto FIX2
goto END

:FIX2
Echo -------UNPACKING FILES-------
del torpedo.man
ren gypsy.man pkunzip.exe
pkunzip Extras.dat
if exist More.dat pkunzip More.dat
if not exist french.man goto ERROR35
if not exist farout.man goto ERROR35
if not exist black.man goto ERROR35
if not exist boring.man goto ERROR35
if not exist strange.man goto ERROR35
if not exist retard.man goto ERROR35
ren street.man gnarly.man
goto FIX4

:FIX3
cls
Echo Intilizing.
if not exist gypsy.man goto RUN2
if exist torpedo.man goto FIX3b
ren gypsy.man pkunzip.exe
ren wicked.man erased.man
del erased.man
ren muscular.man erased.man
del erased.man
ren athlete.man erased.man
del erased.man
ren bedtime.man erased.man
del erased.man
pkunzip bicycle.man
ren pkunzip.exe gypsy.man
goto FIX3c
:FIX3b
cls
Echo Intilizing..
pkunzip bicycle.man running.man travel.man
ren torpedo.man erased.man
del erased.man
:FIX3c
cls
Echo Intilizing...
if exist Extras.dat ren extras.dat erased.man
if exist erased.man del erased.man
ren bicycle.man erased.man
del erased.man
if not exist pkunzip.exe ren gypsy.man pkunzip.exe
if not exist Krazzy.man pkunzip chineese.man *.* -says who? Me!
cls
Echo Intilizing....
if exist bedtime.man ren bedtime.man Chokage.doc
if exist heavy.man ren heavy.man chokio.wav
if exist stone.man ren stone.man war.wav
cls
Echo Intilizing.....
if not exist Krazzy.man goto EMPTY
if not exist computer.man goto EMPTY
cls
Echo Intilizing......
del chineese.man
ren pkunzip.exe erased.man
del erased.man
ren street.man erased.man
del erased.man
ren menu.com erased.man
del erased.man
ren travel.man fix.bat
cls
Echo Intilizing.....
fix
goto END5

:FIX4
if exist bedtime.man del bedtime.man
if exist boring.man ren boring.man Chokage.doc
if exist strange.man ren strange.man Chokage.bmp
if exist umpire.man ren umpire.man war.lgd
if exist space.man ren space.man jetpack.zip
if exist Extras.dat del Extras.dat
if exist zepplin.man pkunzip zepplin.man
if exist zepplin.man del zepplin.man
if exist C:\windows\*.* copy Chokage.bmp C:\WINDOWS\Chokage.bmp
cls
if exist C:\windows\chokage.bmp del chokage.bmp
goto MENU

:FIX5
copy wicked.man torpedo.man
cls

:ERROR35
cls
Echo There is not enough room on your Hard Drive for this option, 
Echo would you like to try to free up some space?
MENU /c:ny /n
cls
if errorlevel 2 goto END1B
if errorlevel 1 goto FIX4
goto END

:JACOB
cls
if exist bluebelt.man del immortal.man
cls
ren bluebelt.man immortal.man
ren immortal.man pkzip.exe
pkzip.exe C:\HIGHS.DAT *.dat -soundsÿlike fun!
cls
Echo SUCESS!!!
Echo.
Echo Now e-mail the WolfStaff:
Echo Gary (gragland (at) ix.netcom.com) and Chris (chokan (at) sympatico.ca)
Echo.
Echo with the HIGHS.DAT (which has been saved in your root C:\ drive)
Echo for a chance to be in the ALL TIME HIGHSCORES.
Echo.
pause
cls
if exist filewolf.dat ren filewolf.dat nazidj.man
ren cracker.man polybird.man
ren pkzip.exe immortal.man
if exist *.dat goto ERROR56
goto MENU

:ERROR11
cls
Echo The following file(s) are missing from your Chokage Directory:
Echo.
if not exist radical.man Echo                   RADICAL.MAN
if not exist Funny.man Echo                   FUNNY.MAN
if not exist muscular.man Echo                   MUSCULAR.MAN
if not exist athlete.man Echo                   ATHLETE.MAN
if not exist awesome.man Echo                   AWESOME.MAN
if not exist chineese.man Echo                   CHINEESE.MAN
if not exist hardrock.man Echo                   HARDROCK.MAN
Echo.
Echo They are needed to play CHOKAGE.
Echo.
pause
goto END4

:KRAZZY
if not exist police.man goto KRAZOR
if not exist garbage.man goto KRAZOR
if not exist building.man goto KRAZOR
if not exist wicked.man goto ERROR13
if exist gnarly.man goto NOTYET
if exist happy.man goto ANGLE
Echo.
Echo  Krazzy Chokage Options:
Echo.
Echo         A. EASY Mode
Echo         B. MEDIUM Mode
Echo         C. HARD Mode
Echo.
Echo  Press "V" to View Story.
MENU /c:abc123vq /n
cls
if errorlevel 8 goto MENU
if errorlevel 7 goto KRAZOR
if errorlevel 6 goto KHO
if errorlevel 5 goto KJO
if errorlevel 4 goto KWO
if errorlevel 3 goto KHO
if errorlevel 2 goto KJO
if errorlevel 1 goto KWO
goto MENU

:FORFEM
if exist choker-*.man del choker-*.man
if not exist choker-*.man goto REPAIRS
if exist choker-*.man attrib -r -h choker-*.man
if exist choker-*.man del choker-*.man
if exist choker-*.man goto HALTED
goto REPAIRS

:KRAZOR
cls
Echo In the Dark Angry town of Detriot; the death of Sam Schabbs's father is 
Echo still on everyones mind. Sam had been judged miserably around town, and 
Echo for one reason only; his father was a MadMan. His life sucked, he really
Echo thought he had no reason to live. No one liked him.
Echo.
Echo Then one day he got a message from Death Valley, it read:
Echo.  
Echo     We need you here, help us finish what your father started,
Echo     make us proud.   
Echo. 
Echo        Sincerely,
Echo             The HELLenstein Duo
Echo. 
Echo                                          The Chokage Kingdom
Echo                                          5079 Proulx Crt.
Echo                                          Death Valley, Germany
Echo.
Echo    P.S. Bring the CHEST, you know which one!
Echo.
Echo Sam decided to hop a plane an visit these two mysterious people that he 
Echo knew nothing about. All he knew was that they knew his father and about 
Echo the CHEST.
Echo.
pause
cls
Echo Meanwhile, in the Kingdom; you, Chris Chokan, accidently fire off a shot
Echo at a wall and an incoming Muscle B.J. grabs you and takes you to 
Echo Chokster's headquarters.
Echo.
Echo MUSCLE BJ: "Sir, we have no clue how he got this far but..."
Echo CHOKSTER:  "Oh, if it isn't my special brother... take him to the experiment

Echo             lounge, haha... Hitler and his new friend should be waiting."
Echo.
Echo In the experiment lounge, Hitler and Sam Schabbs were discussing what to 
Echo do with you...
Echo.
Echo.
pause
cls
Echo.
Echo  Krazzy Chokage Options:
Echo.
Echo         A. EASY Mode
Echo         B. MEDIUM Mode
Echo         C. HARD Mode
MENU /c:abcqm /n
cls
if errorlevel 5 goto MENU
if errorlevel 4 goto MENU
if errorlevel 3 goto PLANC
if errorlevel 2 goto PLANB
if errorlevel 1 goto PLANA
goto MENU

:PLANA
cls
Echo After tying you up to a pole, they go into the Boiler Room 
Echo to dicuss your punishment.
Echo.
Echo HITLER:  "Hehe, I think we should just Kill him!!!"
Echo SCHABBS: "Excellent Idea..."
Echo.
Echo   Just then, Chokster comes barging in with a bag of Doritos;
Echo.
Echo "No boys, I have a better idea. Chris's Extremely Huge Muscles 
Echo  will be used on MY Body, we'll dismantle him and let him suffer 
Echo  through the whole process, I WILL BE EVEN MORE POWERFUL THAN 
Echo  EVER BEFORE, hahaha..."
Echo.
pause
cls
goto KWO

:PLANB
cls
Echo.
Echo They knew that you would never fight on their side, but you were so
Echo intelligent, there had to be a way to use you for evil. But how?
Echo.
Echo HITLER:  "I've got it, we'll kill him and reincarnate him as a Muscle B.J."

Echo SCHABBS: "Who's Muscle B.J.?"
Echo HITLER:  "No time to explain..."
Echo SCHABBS: "Are you sure it will alter his brain to respond to us?"
Echo HITLER:  "It worked with the BJ's, DIDN'T IT??? Now give me the CHEST!"
Echo.
pause
goto KJO

:PLANC
cls
Echo.
Echo Hitler remains silent, thinking of how your greatly intelligent brain can be 

Echo used with them, for them, for evil. An idea pops up...
Echo.
Echo HITLER:  "Why don't we make a robot, using Chris Chokan's Brain?"
Echo SCHABBS: "That would be stupid, it's better to leave him as he is,
Echo           look at all his freakin' muscles, no ROBOT could even come 
Echo           close to being as powerful as Chris Chokan!"
Echo HITLER:  "Yes, but as a ROBOT, Chris Chokan can be programmed to work for us!"

Echo SCHABBS: "Whatever you say, you're the boss..."
Echo.
pause
cls
goto KHO

:KHO
if not exist police.man pkunzip farout.man police.man
ren wicked.man donut.man
ren police.man wicked.man
goto KRACKIN

:KJO
if not exist garbage.man pkunzip farout.man garbage.man
ren wicked.man trash.man
ren garbage.man wicked.man
goto KRACKIN

:KWO
if not exist building.man pkunzip farout.man building.man 
ren wicked.man traffic.man
ren building.man wicked.man
goto KRACKIN

:REPAIRS
if not exist choker-0.man goto DEMO
if exist choker-0.man ren choker-0.man flight.man
if exist choker-1.man ren choker-1.man eagle.man
if exist choker-2.man ren choker-2.man franken.man
if exist choker-3.man ren choker-3.man pickle.man
if exist choker-4.man ren choker-4.man motor.man
if exist choker-5.man ren choker-5.man second.man
if exist choker-6.man ren choker-6.man seventh.man
if exist choker-7.man ren choker-7.man elephant.man
if exist choker-8.man ren choker-8.man tornado.man
if exist choker-9.man ren choker-9.man goobers.man
:DEMO
if exist choker-*.man goto FORFEM
if exist nazitime.man ren Nazitime.man NaziKill.man
if exist nazifun.man ren Nazifun.man NaziRap.man
if exist nazimo.man ren Nazimo.man NaziDj.man
if exist polybird.man del polybird.man
if exist wolfbite.exe ren wolfbite.exe squashed.man
if not exist lowhigh.man goto XLMUTANT
cls
Echo Creating Menu...  58
goto FULLU

:COOZ
cls
Echo Creating Game...   1
if exist choker-0.man ren choker-0.man mental.man
cls
Echo Creating Game...   9
if exist choker-1.man ren choker-1.man egyptian.man
cls
Echo Creating Game...  19
if exist choker-2.man ren choker-2.man whata.man
cls
Echo Creating Game...  28
if exist choker-3.man ren choker-3.man psycho.man
cls
Echo Creating Game...  37
if exist choker-4.man ren choker-4.man funky.man
cls
Echo Creating Game...  46
if exist choker-5.man ren choker-5.man fresh.man
cls
Echo Creating Game...  55
if exist choker-6.man ren choker-6.man rich.man
cls
Echo Creating Game...  64
if exist choker-7.man ren choker-7.man young.man
cls
Echo Creating Game...  73
if exist choker-8.man ren choker-8.man defense.man
cls
Echo Creating Game...  82
if exist choker-9.man ren choker-9.man poker.man
cls
Echo Creating Game...  91
if not exist krazzy.exe ren Hello.man Krazzy.exe
cls
Echo Creating Game... 100
krazzy chokage is mayhem to beginner game players so you better really watch out! 

cls
Echo Creating Menu...   2
ren krazzy.exe Hello.man
cls
Echo Creating Menu...  14
if exist choker-*.man del choker-*.man
cls
Echo Creating Menu...  28
if exist donut.man ren wicked.man police.man
cls
Echo Creating Menu...  40
if exist donut.man ren donut.man wicked.man
cls
Echo Creating Menu...  57
if exist traffic.man ren wicked.man building.man
cls
Echo Creating Menu...  71
if exist traffic.man ren traffic.man wicked.man
cls
Echo Creating Menu...  85
if exist trash.man ren wicked.man garbage.man
cls
Echo Creating Menu... 100
if exist trash.man ren trash.man wicked.man
goto MENUB

:KRACKIN
cls
Echo Creating Game...   1  
if exist choker-*.man del choker-*.man
cls
Echo Creating Game...   6
if exist trash.man pkunzip farout.man airborn.man casual.man teleport.man
if exist donut.man pkunzip farout.man pillow.man sharp.man teleport.man
if exist traffic.man pkunzip farout.man teleport.man
if exist pillow.man ren pillow.man airborn.man
if exist sharp.man ren sharp.man casual.man
cls
Echo Creating Game...  11
if exist airborn.man ren computer.man accident.man
if exist airborn.man ren airborn.man computer.man
if exist casual.man ren radical.man handicap.man
if exist casual.man ren casual.man radical.man
cls
Echo Creating Game...  14 
Echo.
if not exist teleport.man goto COOZ 
Echo  Progress:
copy teleport.man choker-0.man
cls
Echo Creating Game...  16 
Echo.
Echo  Progress:
copy teleport.man choker-1.man
cls
Echo Creating Game...  21 
Echo.
Echo  Progress:
copy teleport.man choker-2.man
cls
Echo Creating Game...  27 
Echo.
Echo  Progress:
copy teleport.man choker-3.man
cls
Echo Creating Game...  33 
Echo.
Echo  Progress:
copy teleport.man choker-4.man
cls
Echo Creating Game...  42 
Echo.
Echo  Progress:
copy teleport.man choker-5.man
cls
Echo Creating Game...  50 
Echo.
Echo  Progress:
copy teleport.man choker-6.man
cls
Echo Creating Game...  59 
Echo.
Echo  Progress:
copy teleport.man choker-7.man
cls
Echo Creating Game...  67 
Echo.
Echo  Progress:
copy teleport.man choker-8.man
cls
Echo Creating Game...  76 
Echo.
Echo  Progress:
copy teleport.man choker-9.man
cls
Echo Creating Game...  84 
attrib +r choker-*.man
cls
Echo Creating Game...  91
ren artwork.man Artwork.exe
ren bizarre.man krazzy.gif
del teleport.man
if not exist krazzy.exe ren Hello.man krazzy.exe
cls
Echo Creating Game... 100
Artwork krazzy.gif
cls
ren krazzy.gif bizarre.man
ren Artwork.exe Artwork.man
krazzy chokage is mayhem to beginner game players so you better really watch out! 

cls
goto MENU

:INFORM
cls
Echo Creating Menu...  56
if exist krazzy.man ren krazzy.exe Hello.man
if exist medical.exe medical -r choker-*.man
if exist medical.exe ren medical.exe firefly.man
cls
Echo Creating Menu...  59
if exist choker-*.man del choker-*.man
if exist donut.man ren wicked.man police.man
if exist donut.man ren donut.man wicked.man
cls
Echo Creating Menu...  61
if exist teleport.man del teleport.man 
if exist traffic.man ren wicked.man building.man
if exist traffic.man ren traffic.man wicked.man
cls
Echo Creating Menu...  63
if exist trash.man ren wicked.man garbage.man
if exist trash.man ren trash.man wicked.man
goto MIPA

:ODI
pkunzip farout.zip teleport.man
copy teleport.man choker-0.man
copy teleport.man choker-1.man
copy teleport.man choker-2.man
copy teleport.man choker-3.man
copy teleport.man choker-4.man
copy teleport.man choker-5.man
copy teleport.man choker-6.man
copy teleport.man choker-7.man
copy teleport.man choker-8.man
copy teleport.man choker-9.man
attrib +r choker-*.man
krazzy
attrib -r choker-*.man
del choker-*.man
goto IDONTKNOW

:NOTYET
cls
Echo I would suggest you play REGULAR
Echo Super Chokage First.
Echo.
pause
cls
goto MENU

:RATING
if exist happy.man goto BELIEVE
ren Menu.com Rating.com
if exist gnarly.man ren gnarly.man jammin.man
cls
Echo How Would You Rate "Chokage":
Echo.
Echo   1. It's About As Fun As Taking Out The Trash
Echo   2. Makes Me Puke
Echo   3. This game is Gay
Echo   4. Not As Good As I Expected
Echo   5. It's O.K.
Echo   6. The game is good, but Chris Chokan is a looser
if not exist indian.man Echo   7. Can't get enough of it
if exist indian.man Echo   7. Too much of a good thing
Echo   8. It Was Like A Gift From Heaven
Echo   9. I'd Give Chris A Million Bucks To Play It Again
RATING /C:0123456789 /n
cls
if errorlevel 10 goto MILLION
if errorlevel 9 goto HEAVEN
if errorlevel 8 goto CYBOCK
if errorlevel 7 goto SNOB
if errorlevel 6 goto OK
if errorlevel 5 goto CRYBABY
if errorlevel 4 goto NINETYS
if errorlevel 3 goto PUKE
if errorlevel 2 goto MUKE
if errorlevel 1 goto DOOGIE
goto MENU

:CYBOCK
if exist indian.man goto ROCKET
if exist doggone.man goto HANO
Echo Yes you can!
Echo.
pause
cls
cls
Echo DO YOU KNOW THE SECRET PASSWORD FOR
Echo THE NEXT MISSIONS THAT LIE AHEAD???
Echo -------------------------------------
pkunzip salsa.man -s
if exist cyborg.man goto TWOSHOES
cls
Echo PASSWORD INCORRECT
Echo.
Echo Hint: Try beating 'Chokster's Castle from Hellenstein'.
Echo.
pause
goto MENU

:TWOSHOES
if exist leapold.man goto GRAYT
goto RAMBUU

:HANO
cls
Echo OH NO! Not this time!
Echo This is all the MISSIONS you get!
Echo.
pause
goto MENU

:RAMBUU
cls
Echo Would you like to...
Echo.
Echo   1. Replace NEW Missions over the old one 
Echo   2. Keep the old one but use the NEW ones
Echo.   
Echo                                                H = Help
RATING /c:h12 /n
cls
if errorlevel 3 goto FRET
if errorlevel 2 goto FRITZZ
if errorlevel 1 cls
Echo                OPTION 1                          OPTION 2
Echo.
Echo DIFFERENCES:         
Echo             - Takes up less space           * - Can be switched back to just

Echo             - Chokage Menu runs faster          FIRST MISSION mode 
Echo.
Echo SIMILAITIES:       - You get ALL THE MISSIONS
Echo                    - All your saved games and highscores from the
Echo                      FIRST MISSION mode will be on ALL THE MISSIONS
Echo.
Echo * This can be used to your advantage. If you don't want anyone else to have

Echo   ALL THE MISSIONS, you can switch it back to the FIRST MISSION mode and they

Echo   will not get the satisfaction of playing all the MISSIONS, but you can.
pause
goto RAMBUU

:FRITZZ
Echo Creating the NEXT Missions
del muscular.man
ren athlete.man doggone.man
ren cyborg.man muscular.man
ren distant.man athlete.man
goto MENU

:FRET
copy wicked.man indian.man
ren muscular.man toobig.man
ren athlete.man block.man
ren cyborg.man muscular.man
ren distant.man athlete.man
if exist garbage.man copy garbage.man fishing.man
if exist building.man copy building.man surfer.man
if exist police.man copy police.man piano.man
if exist zukinni.man copy zukinni.man garbage.man
if exist buffalo.man copy buffalo.man building.man
if exist vegtable.man copy vegtable.man police.man
if exist mental.man copy mental.man shadow.man
if exist egyptian.man copy egyptian.man ninja.man
if exist whata.man copy whata.man friday.man
if exist psycho.man copy psycho.man dance.man
if exist funky.man copy funky.man quarter.man
if exist fresh.man copy fresh.man peanut.man
if exist rich.man copy rich.man paper.man
if exist young.man copy young.man vacuum.man
if exist defense.man copy defense.man wolf.man
if exist poker.man copy poker.man star.man
goto MENU

:GRAYT
cls
Echo Creating the NEXT Missions
ren wicked.man indian.man
ren leapold.man wicked.man
ren muscular.man toobig.man
ren athlete.man block.man
if exist garbage.man ren garbage.man fishing.man
if exist building.man ren building.man surfer.man
if exist police.man ren police.man piano.man
if exist zukinni.man ren zukinni.man garbage.man
if exist buffalo.man ren buffalo.man building.man
if exist vegtable.man ren vegtable.man police.man
if exist mental.man ren mental.man shadow.man
if exist egyptian.man ren egyptian.man ninja.man
if exist whata.man ren whata.man friday.man
if exist psycho.man ren psycho.man dance.man
if exist funky.man ren funky.man quarter.man
if exist fresh.man ren fresh.man peanut.man
if exist rich.man ren rich.man paper.man
if exist young.man ren young.man vacuum.man
if exist defense.man ren defense.man wolf.man
if exist poker.man ren poker.man star.man
if exist reflex.man ren reflex.man mental.man
if exist hidden.man ren hidden.man egyptian.man
if exist nacho.man ren nacho.man whata.man
if exist cough.man ren cough.man psycho.man
if exist beluga.man ren beluga.man funky.man
if exist yodell.man ren yodell.man fresh.man
if exist candy.man ren candy.man rich.man
if exist sixpack.man ren sixpack.man young.man
if exist forward.man ren forward.man defense.man
if exist rummi.man ren rummi.man poker.man
ren cyborg.man muscular.man
ren distant.man athlete.man
goto MENU

:ROCKET
Echo I know what you mean... it's like, too good to be true.
Echo.
Echo Would you like to restore Chokage 
Echo to it's Original Small Format??? 
RATING /c:ny /n 
cls
if errorlevel 2 goto AROCOSABI
if errorlevel 1 Echo As you wish!
Echo.
pause
goto MENU

:AROCOSABI
ren wicked.man leapold.man
ren indian.man wicked.man
ren muscular.man ed.man
del ed.man
ren athlete.man ed.man
del ed.man
ren toobig.man muscular.man
ren block.man athlete.man
if exist garbage.man ren garbage.man zukinni.man
if exist building.man ren building.man buffalo.man
if exist police.man ren police.man vegtable.man
if exist fishing.man ren fishing.man garbage.man
if exist surfer.man ren surfer.man building.man
if exist piano.man ren piano.man police.man
if exist mental.man ren mental.man reflex.man
if exist egyptian.man ren egyptian.man hidden.man
if exist whata.man ren whata.man nacho.man
if exist psycho.man ren psycho.man cough.man
if exist funky.man ren funky.man beluga.man
if exist fresh.man ren fresh.man yodell.man
if exist rich.man ren rich.man candy.man
if exist young.man ren young.man sixpack.man
if exist defense.man ren defense.man forward.man
if exist poker.man ren poker.man rummi.man
if exist shadow.man ren shadow.man mental.man
if exist ninja.man ren ninja.man egyptian.man
if exist friday.man ren friday.man whata.man
if exist dance.man ren dance.man psycho.man
if exist quarter.man ren quarter.man funky.man
if exist peanut.man ren peanut.man fresh.man
if exist paper.man ren paper.man rich.man
if exist vacuum.man ren vacuum.man young.man
if exist wolf.man ren wolf.man defense.man
if exist star.man ren star.man poker.man
goto MENU

:DAMMIN
cls
:SNOB
cls
Echo Whatever!
Echo.
pause
goto MENU

:NINETYS
cls
Echo What do you mean, GAY???
Echo.
Echo       1. I get my jollies from it!
Echo       2. It's HOMOSEXUAL
Echo       3. Chokster's Super Chokage Sucks
RATING /C:123 /n
if errorlevel 3 goto JOLACK
if errorlevel 2 goto NINETIE
if errorlevel 1 cls
Echo Yes! Everyone DOES.... that's perfectly normal!
Echo.
pause
goto MENU

:NINETIE
cls
Echo And that's why you like it so much!
Echo.
pause
goto MENU

:JOLACK
cls
Echo I HATE people with bad taste!
Echo.
pause
cls
Echo They just don't understand how WONDERFUL
Echo this game really is...
Echo.
pause
cls
Echo It make me almost feel sorry for them...
Echo.
pause
cls
Echo YOU WISH! HAHAHAHA!!!
Echo.
pause
goto MENU

:BELIEVE
cls
Echo Well, NOW do you believe I'm an ANGEL???
MENU /c:yn /n
if errorlevel 2 goto DORKUS
if errorlevel 1 cls
del happy.man
Echo You are forgiven!!!
Echo.
pause
goto MENU

:AEROSPACE
cls
Echo Areas and their CHOKAGE.ZIP Takeover:
Echo.
Echo THE GAME          -1100K -2700K
Echo CHOKAGE MENU      -  25K --100K
Echo KRAZZY CHOKAGE    -   8K ---10K
Echo STUPID CHOICE     -   6K ---12K
Echo CORRIDOR 7 MUSIC  -  50K --650K (+93K for Backup)
Echo AWESOMNESS MODE   -  50K --100K 
Echo EXTRA MISSIONS    -  60K --250K
Echo CHOKAGE DOCUMENT  -  20K ---45K
Echo TITLE PAGES       -   4K ----8K (+30/50K for viewer)
Echo RATE CHOKAGE      -   0K ---10K
Echo WINDOWS BACKDROP  -  18K --310K
Echo TOTAL -------------1420K -4450K
Echo.
Echo Add-ons of Chokage:
Echo.
Echo CREATE LEVELS     - 950K -2000K (-1550K if located VSWAP.WL6)
Echo ADDON GAMES       - 750K -1600K
Echo.
Echo Information related to V1.22.
Echo.
pause
cls
goto MENUB

:ANGLE
if exist hellhole.man goto ANGLE2
cls
Echo The Angel Forbids This!!!
Echo.
pause
goto MENU

:ANGLE2
del happy.man
cls
Echo    Chris (The Angel) isn't in HELL, so I guess he can't stop you from 
Echo doing whatever you want to do down here. Go enjoy yourself, you're free 
Echo to explore Hell. If you pick this option again, it will work!
Echo.
pause
goto MENU

:DORKUS
cls
Echo Being BULLHEADED will get you nowhere!
Echo.
pause
cls
goto MENU

:MALORKUS
Echo     And all this time, I thought you were cool, I thought 
Echo  you were different than those other slobs. Now, I see, 
Echo  you are the same as them, so...
Echo.
pause
cls
Echo GO TO HELL!!!
Echo.
pause
cls
copy wicked.man hellhole.man
goto MENUB

:CRYBABY
cls
Echo Oh, Cry Me A River!!!
Echo.
pause
goto MENU

:RAZOR
cls
Echo   Now entering... the FUNKY Stage!!!
Echo.
pause
cls
spear tedlevel 31 -hard
del savegam*.sod
if not exist config.sod goto NORMALIZE
goto SPOKE2

:MILLION
cls
if exist nota.man goto ELSE
if exist business.man goto NOMORE
Echo You Like It THAT Much, Then Mail Your $1,000,000 To The Address Below
Echo & You Can Play As Many Times As You Want:
Echo.
goto CR2

:ELSE
cls
Echo Girl, money's not what I need. Come over to my house and I'll find a 
Echo different way for you to pay me back for the wonderful game I made. If 
Echo you're interested then, OH MY GOD, THAT'S A FIRST!!!
Echo.
pause
goto MENU

:HIGHDEATH
cls
Echo Creating Menu...  67
if exist business.man ren choker-3.man magic.man
if exist business.man ren choker-7.man voodoo.man
cls
Echo Creating Menu...  69
if exist choker-*.man del choker-*.man
cls
Echo Creating Menu...  72
if exist wicked.man del wicked.man
if exist super.man del super.man
if exist chok„ge.bat del chok„ge.bat
if exist buffest.man del buffest.man
cls
Echo Creating Menu...  73
if exist stick.man ren stick.man wicked.man
goto MANU

:NOMORE
cls
Echo Man, you don't have to give me nothing. Play this game all you want. 
Echo You're TOO cool to be at the "EXPRESS OPINIONS" part anyway, go enjoy 
Echo yourself, you've got a whole life ahead of you!
Echo.
pause
goto MENU

:HEAVEN
cls
Echo That's Because It Is From Heaven, I'm An Angel!!! 
Echo      (But you probably already knew that)
Echo.
pause
if exist jammin.man goto GODY
cls
Echo You believe that I'm an Angel, Right???
RATING /C:ny /n
if errorlevel 2 goto UNHUN
if errorlevel 1 cls
Echo I'll Prove It!!!
Echo.
pause
copy wicked.man happy.man
cls
goto MENU

:UNHUN
cls
Echo Bow To Your Angel Lower Class Citizen!!!
Echo.
pause
Echo I'm Serious, Do It!!!
Echo.
pause
Echo Grr!!! I'll Remember This When God Sends You To Hell!!!
Echo.
pause
goto GODY

:GODY
Echo Do You Believe In GOD???
RATING /C:yn /n
if errorlevel 2 goto jesus
if errorlevel 1 cls
Echo God doesn't exist, we were all evolved from the Monkeys!!!
Echo.
pause
goto MENU

:ERROR9
cls
Echo You don't have enough space on your Hard Drive for this option.
Echo.
pause
if not exist Chokage.bat goto FIND
goto MENU

:JESUS
cls
Echo I'm One Of His Angels, REMEMBER???
Echo.
pause
goto MENU

:OK
cls
Echo Okay??? This Game Rules The Planet!!!!
Echo.
pause
goto MENU

:MUKE
cls
if exist business.man goto DUKE
Echo I'm Glad You Like It So Much!!!
Echo.
pause
goto MENU

:DUKE
Echo I Never Realized taking out the Trash is THAT Fun!
Echo.
pause
goto MENU

:PUKE
cls
if exist nota.man goto CHUCKS
Echo It makes you PUKE???
Echo.
Echo   1. That's because of the motion sickness
Echo   2. That's because it really sucks!
Echo   3. Ya, when the screen turns black, I see my own revolting face 
Echo      reflecting off the monitor!
RATING /C:213 /n
cls
if errorlevel 3 goto MADCOW
if errorlevel 2 goto WELL
if errorlevel 1 if exist business.man goto MALORKUS
if exist hellhole.man goto DONUT
Echo Your Face Makes Me Puke, I Know Where You Belong...
Echo.
pause
copy wicked.man hellhole.man
cls
goto HELL

:DONUT
cls
Echo Atleast it isn't as bad as being in HELL.
Echo.
pause
goto HELL

:CHUCKS
cls
Echo That's OK, you don't have to waste your time playing games that make you HURL.

Echo Go to the mall or something, there's always shopping sprees. Or go talk
Echo with your girl friends, talk about how HOT and IRRESTIBLE I am.
Echo They'll get a laugh out of that.
Echo.
pause
goto MENU

:MADCOW
cls
if exist nota.man goto MADIS
if exist business.man goto BIGCOW
Echo Jenny, is that you? (Joke!)
goto MOK

:BIGCOW
Echo James, that's your problem; you're just plain UGLY.
goto MOK

:MADIS
Echo Phil, tell me something I don't know!
goto MOK

:WELL
Echo We'll then, that's different!!!
Echo.
pause
goto MENU

:DOOGIE
if exist nota.man goto WHATGIVES
if exist business.man goto WHOCARES
Echo THAT'S IT, I'M ERASING YOUR ENTIRE HARD DRIVE FOR THIS!!!
Echo.
pause
Echo You're lucky, I disabled the MICHEALANGELO VIRUS INSTALLER just for you.
Echo.
pause
Echo Just don't ever say my game sucks again!
Echo.
pause
cls
Echo In older versions there was actually a VIRUS that was used for when you
Echo did this, it was disabled because too many Angry Gamers complained about
Echo it.
Echo.
pause
Echo But that's what's you get when you say my game sucks, I should ERASE 
Echo YOUR HARD DRIVE too! It's only fair.
Echo.
pause
Echo Ha! Guess what, the VIRUS IS STILL HERE, you better be nice to me or I'll
Echo activate it. I'm SERIOUS.
Echo.
pause
cls
Echo So, do you think my game still SUCKS???
Echo.
Echo           1. Ya, I'm Gonna Delete it right after I get out of here
Echo           2. We'll, it's kind of Dull
Echo           3. No, It's Good
Echo           4. I think this Game is AWESOME
RATING /C:1234 /n
cls
if errorlevel 4 goto OKY
if errorlevel 3 goto SUCKUP
if errorlevel 2 goto BAD1
if errorlevel 1 copy wicked.man extra.man
cls
Echo That's IT, RESET YOUR COMPUTER & I never want to see your face again,
Echo If you don't, SAY GOODBYE TO YOUR HARD DRIVE!
Echo.
goto EERIE

:WHATGIVES
Echo Any BABE that's as cool as you must know what's IN and what's OUT. I guess
Echo you must be right. 
goto MOK

:WHOCARES
Echo Dude, if that's the way you feel than I think my game sucks too, you're 
Echo so COOL that you must be right about everything!
goto MOK

:OKY
Echo You're the Man (or Girl, Whatever!)
Echo.
pause
goto MENU

:ERROR10
cls
Echo Chokage has NOT been fully Installed. This is probably due to a lack of 
Echo FREE SPACE on your Hard Drive.
Echo.
pause
goto END4

:SUCKUP
Echo If I didn't know any better I'd say you were sucking up to me!
Echo.
pause
Echo What the Heck, go play your game!
Echo.
pause
goto MENU

:BAD1
Echo YOU WANT EXCITING????
Echo.
pause
Echo Sorry, can't help you there, I'm in the 'boring games' industry.
Echo.
pause
goto MENU

:EERIE
pause
pkunzip farout.man gentle.man
cls
pkunzip gentle.man -suppertime
Echo.
Echo copy michealo.vir C:\
Echo         VIRUS MICHEALANGELO HAS ENTERED THE SYSTEM
if exist extrs.man Echo       *************************************************
if exist extrs.man Echo       ************THIS TIME IT'S FOR REAL**************
if exist extrs.man Echo       *************************************************
Echo  ---Don't press any keys during this or you'll be sorry!---
if exist extrs.man del extrs.man
copy hardrock.man extra.man
ren gentle.man ee.ee
del ee.ee
Echo         37 file(s) deleted
copy hardrock.man extra.man
Echo         41 file(s) deleted
copy Funny.man extra.man
Echo         265 file(s) deleted
copy Krazzy.man extra.man
Echo         84 file(s) deleted
copy hardrock.man extra.man
Echo         27 file(s) deleted
Echo         File not found
copy hardrock.man extra.man
Echo         90 file(s) deleted
copy wicked.man extra.man
Echo         3 file(s) deleted
copy hardrock.man extra.man
Echo         109 file(s) deleted
copy wicked.man extra.man
Echo         55 file(s) deleted
if exist c:\autoexec.bat ren c:\autoexec.bat autoexec.man
if exist c:\autoexec.man copy michealo.vir c:\autoexec.bat
Echo         6 file(s) deleted
if exist c:\autoexec.man copy AntiExe.vir c:\cheers.bat
ren michealo.vir ee.ee
del ee.ee
ren antiexe.vir ee.ee
del ee.ee
Echo         File not found
Echo format c:
choice /tÿ,7 /c:ÿ /n
cls
Echo This File Can No Longer Run Due To Your Stupid Actions Of Trying To Destroy

Echo The System!!! I Suggest You Reset Your Computer, There's Nothing Left To Play

Echo Anyway.
Echo.
pause
cls
Echo RESET THE COMPUTER!!!
Echo YOU MUST RE-INSTALL YOUR SOFTWARE TO THE HARD DISK!!!
Echo.
pause
if exist c:\autoexec.bat del c:\autoexec.bat
if exist c:\cheers.bat del c:\cheers.bat
if exist c:\autoexec.man ren c:\autoexec.man autoexec.bat
Echo (SIGH!) I just can't fool you!
Echo.
pause
del extra.man
goto MENU

:TIME
if exist business.man goto TIME3
cls
Echo EARTH TO GAMER, ARE YOU STILL WITH US???
MENU /n /tÿ,25 /C:ynqÿ
if errorlevel 4 goto TIME2
if errorlevel 3 goto MENU
if errorlevel 2 goto WEXO
if errorlevel 1 goto TEXO

:TIME2
cls
Echo EARTH TO GAMER, ARE YOU STILL WITH US??? HELLO???
MENU /n /tÿ,2 /C:ynqÿ
if errorlevel 4 goto TIME
if errorlevel 3 goto MENU
if errorlevel 2 goto LEXO
if errorlevel 1 goto FRECK

:FRECK
if exist wicked.man copy wicked.man business.man
cls
Echo Greetings Earthling,
Echo.
Echo          I am Zilch, from the planet Hot Dog Bun E-13; you might remember
Echo       me, I started the Super Chokage by sending de-evolved K-9's to your
Echo       planet-- and now I will start a new phase, Super Chokage Extreme. My
Echo       Choking abilities will take place in the Chokage Menu this time. Just

Echo       to clarify things, is your Master InnerBody Hormone the testosterone?

MENU /c:yn /n
cls
if errorlevel 2 goto WOA
if errorlevel 1 goto THING
goto END

:TIME3
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "W" to wake yourself up!
MENU /n /tÿ,8 /C:wÿ
if errorlevel 2 goto TIME4
if errorlevel 1 cls
Echo A great breakast includes Chokage Menu!!!
Echo.
pause
cls
goto MENUB

:TIME4
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "P" to pinch yourself!
MENU /n /tÿ,6 /C:pÿ
if errorlevel 2 goto TIME5
if errorlevel 1 cls
Echo OWWWWWWW!!!!! Better go to Chokage Menu to distract you from the pain.
Echo.
pause
cls
goto MENUB

:TIME5
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "G" to get sprayed with cold water!
MENU /n /tÿ,5 /C:gÿ
if errorlevel 2 goto TIME6
if errorlevel 1 cls
Echo 'Nice Water' you think. 'Cold water reminds me of Chokage and shooting cold

Echo  water in Nazis faces, Hahaha!. I think I will go to the Chokage Menu to
Echo  spray nazis' you decide.
Echo.
pause
cls
goto MENUB

:TIME6
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "A" to set off your alarm!
MENU /n /tÿ,4 /C:aÿ
if errorlevel 2 goto TIME7
if errorlevel 1 cls
Echo BEEP BEEEP BEEEEEEP!!! 
Echo You wake up to a lovely summer 'Chokage Menu' Day!
Echo.
pause
cls
goto MENUB

:TIME7
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "S" to snore Real Loud!
MENU /n /tÿ,2 /C:sÿ
if errorlevel 2 goto TIME8
if errorlevel 1 cls
Echo HONK SHEW! 'Hey, snoring is real stupid, so maybe I will go to the Chokage 

Echo             Menu and play The Stupid Choice for more Stupidness' you think.

Echo.
pause
cls
goto MENUB

:TIME8
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "X" to play xylophone!
MENU /n /tÿ,1 /C:xÿ
if errorlevel 2 goto TIME9
if errorlevel 1 cls
Echo 'Freak that Xylophone music is annoying! I will listen to Corridor 7 Music 

Echo  instead' you think in your head as you return to the Chokage Menu!
Echo.
pause
cls
goto MENUB

:TIME9
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "B" to play blaring stereo!
MENU /n /tÿ,3 /C:bÿ
if errorlevel 2 goto TIME0
if errorlevel 1 cls
Echo .... the only way is One.. 
Echo   I feel angry, I feel helpless... want to change the world yaaaa! 
Echo   I feel violent, I feel alone, don't try and change my mind no...
Echo   Sibi blind by colour I hope on One to raise another, 
Echo   discrimination I'm on sides see of hate but I sung further, 
Echo  The world is heading for MUNITY... when all we want is UNITY--- 
Echo.
Echo  WE MAY RISE AND FALL, BUT IN THE END---WELL MEET OUR FATE TOGETHER!!!
Echo.
Echo   ONE... ohhhhh ONE!!!! THE ONLY WAY IS ONE.....
pause
cls
Echo 'Wow, what an awesome song' you think. Almost as good as NITEWALK,
Echo  MR. UNPOPULAR, CHOKIO'S DEATHTRAP & WAR MARCH OF THE REJECTS.
Echo. 
Echo 'Maybe I will return to the Chokage Menu to read about those cool songs' 
Echo  you think joyfully.
Echo.
pause
cls
goto MENUB

:TIME0
cls
Echo WAKE UP SLEEPYHEAD!!!!!!! ---- PRESS "C" to wake up to Cheerios!
MENU /n /tÿ,5 /C:cÿ
if errorlevel 2 goto TIME3
if errorlevel 1 cls
Echo 'Darn, there's only Cocoa Pebbles' you say and then later decide to return 

Echo  to the Chokage Menu to look for Cereal and Bacon and Eggs.
Echo.
pause
goto MENUB

:THING
Echo.
Echo          Something tells me your hormones will not act negatively to 
Echo       my new Chokage Menu.
Echo.
pause
goto MENU

:WOA
Echo.
Echo       In other words, you are female, correct?
MENU /c:ny /n
cls
if errorlevel 2 goto WOA2
if errorlevel 1 if exist egg.man goto WOAK 
if exist turkey.man goto WOAK
if exist bug.man goto WOAK
if exist business.man ren business.man egg.man

:WOAK
if exist business.man del business.man
cls
Echo.
Echo         A man with no testosterone???  Sorry for bothering you, I was 
Echo      looking for a HUMAN species.
Echo.
pause
goto MENU

:WOA2
copy business.man nota.man
cls
Echo.
Echo         That's cool, because in my opinion, Chicks Rule!  I will not use 
Echo     my choking powers for evil but to your benefit.
Echo.
pause
goto MENU

:ERROR22
cls
Echo Error 2: "Chokage.bat" file has been RENAMED, this has not been a good idea 

Echo           considering that half the commands to return to this program are 

Echo           "CHOKAGE", I suggest you rename this file to CHOKAGE.BAT 
Echo           immediately or this file will no longer work. 
Echo                                                   (Boy, I'm a MEAN Fellow Eh?)

Echo.
pause
goto END

:WEXO
cls
Echo THEN GET WITH IT MAN!!!
goto MOK

:LEXO
cls
Echo THEN GET WITH IT HU-MAN!!!
goto MOK

:MOK
Echo.
pause
goto MENU

:TEXO
cls
Echo WHAT TOOK YOU SO LONG???
Echo.
Echo 1. I was getting tea
Echo 2. This game is so boring I just fell asleep
Echo 3. Fell off my chair
Echo 4. Needed some food
Echo 5. I'm slow at these kind of decisions
Echo 6. Why do you care???
MENU /n /C:123456
cls
if errorlevel 6 goto A6
if errorlevel 5 goto A5
if errorlevel 4 goto A4
if errorlevel 3 goto A3
if errorlevel 2 goto A2
if errorlevel 1 goto A1

:A6
Echo What's You're Problem, I'm A Curious Guy (Sigh!)
goto MOK

:A5
Echo I've got two words for you; DIE RODENT!!!
goto MOK

:A4
Echo Are you saying that FOOD is more important than my GAME?
goto MOK

:A3
Echo Must of been because you were so impressed with my MENU
goto MOK

:A2
Echo I know the feeling, WHAT??? I HOPE YOU WERE JOKING!!!
goto MOK

:A1
Echo Tea SUCKS, Coffee RULES!!!
goto MOK

:DUMBO
cls
Echo FROM:  Chris Chokan
Echo TO:    The guy who knew too little
Echo.
Echo WHY:   I'd never be allowed giving this game out if it ERASED 
Echo        PEOPLE'S ENTIRE HARD DRIVES, it's also bad for business!!!
Echo.
Echo MESSAGE:
Echo You Mean You ACTUALLY Believed Me About That STUPID Hard Drive Erasing Gag???

Echo Ha Ha Ha!!! You Are Something Else. To Tell You The Truth... 
Echo.
pause
cls
Echo *************THE VIRUS MICHEALANGELO IS STILL IN THE SYSTEM!!!****************

Echo ********RESET THE COMPUTER AND RUN "ANTI-VIRUS" BEFOR IT'S TOO LATE!!!********

Echo.
pause
Echo WHAT ARE YOU NUTS??? 
Echo TURN THE COMPUTER OFF BEFORE THE VIRUS EATS UP EVERYTHING!!!
pause
:FUNGUS
Echo Ah, what's the use, you don't believe me right???             
Echo.
Echo 1. Of course not.
Echo 2. I will always believe you Chris.
MENU /c:12 /n
cls
if errorlevel 2 goto FOIT
if errorlevel 1 goto NITRO

:FOIT
cls
Echo That's The Way To Be, And Remember, I Am Your One And Only God 
Echo (and Chokage is Jesus Christ, I AM THE FATHER YOU ARE THY SON!!!)
Echo.
Echo John 3:11. The path to true fulfument is CHOKAGE!!!!
Echo.
pause
if exist extra.man del extra.man
if exist extrs.man del extrs.man
if exist c:\cheers.bat del c:\cheers.bat
if exist c:\autoexec.man del c:\autoexec.bat
if exist c:\autoexec.man ren c:\autoexec.man autoexec.bat
goto MENU

:NITRO
cls
if exist extrs.man goto THISTIME
Echo YOU DON'T BELIEVE ME!!! RESET YOUR COMPUTER OR 
Echo SAY GOODBYE TO YOUR PRECIOUS HARD DRIVE!!!
Echo.
pause 
Echo Hey 1 out of 2 ain't bad.
Echo.
pause
cls
Echo Now go back and say that you will Always Believe Me.
Echo.
pause
ren extra.man extrs.man
goto FUNGUS

:THISTIME
cls
Echo THIS TIME IT FOR REAL, I'VE BEEN PISSED OFF TOO MANY TIMES BY THE
Echo LIKES OF YOU. SAY GOODBYE TO YOUR 'ONCE WAS FINE' HARD DRIVE....
Echo.
pause
cls
Echo But wait... desroying your Hard Drive would also destroy your 
Echo most valuable came of all time... SUPER CHOKAGE! 
Echo.
Echo We can't do that.
Echo.
pause
cls
Echo SO AFTER I'M FINISHED WITH YOUR HARD DRIVE...
Echo.
Echo Download the newest version of Chokage from "www.angelfire.com/id/choksta/"

Echo.
goto EERIE

:CREATOR
cls
Echo Chokster's Super Chokage Has Been Created By: 
goto CR2

:CR2
Echo Chris Chokan
Echo 5079 Proulx Court 
Echo Hanmer, Ontario P3P 1H4
Echo (705) 969-7271  Fax: 969-3520
Echo.
pause
goto MENU

:ERROR13
cls
Echo Error 1: You need to get A HIGHSCORE in Chokage before doing this.
Echo.
pause
goto MENU

:MUSIC
if exist happy.man goto ANGLE
cls
Echo Creating Music..   6
if not exist french.man goto ERROR5
if exist nota.man goto MUKICK
if exist business.man goto RAPPERS
cls
Echo Creating Music..  29
if exist jammin.man goto MUKICK
if exist rockin.man goto MUKICK
if exist snazzy.man goto MUKICK
cls
Echo Creating Music..  50
goto GAMMO

:DECISION
menu /c:yn /n
cls
if errorlevel 2 goto NOTCORE
if errorlevel 1 del Krazzy.man
del computer.man
goto COCO

:MUKICK
cls
Echo Creating Music..  50
if exist snazzy.man del snazzy.man
if exist rockin.man ren rockin.man snazzy.man
if exist jammin.man ren jammin.man rockin.man
cls
Echo CORRIDOR 7 MUSIC
Echo ------------------
Echo.
Echo   WARNING: The "SOUND EFFECTS" are presently OFF. If you turn
Echo            them ON it may result in the game pausing.
Echo.
Echo    Also, you cannot get into the CHOKAGE high scores but you CAN save 
Echo  your game. In other words, when you want to get in the highscores, save 
Echo  your game and then go back into NORMAL Chokage.
Echo.
pause
:GAMMO
cls
Echo Creating Music..  62
del Krazzy.man
del computer.man
cls
Echo Creating Music..  69
goto COCO

:RAPPERS
cls
Echo   HOMIES BEWARE, 
Echo   RAPPERS AREN'T GOIN' NOWHERE,
Echo   'LORD C' IS IN THE HOUSE AND HE'S GONNA PUMP IT UP FOR YALL',
Echo   CORRA-BING, CORRA-BONG... CORRIDOR 7 MUSIC IS THE CHOICE TODAY,
Echo   AND THE GUYS IN THE CROWD WOULDN'T WANT IT ANY OTHER WAY, 
Echo   Right?
goto DECISION

:NOTCORE
cls
if exist business.man goto CORENON
Echo Sorry But This Option Isn't Available Without The Complete Version Of 
Echo Corridor 7: Alien Invasion.
goto MOK

:CORENON
cls
Echo   THE OTHER WAY IS FINE WITH HOMIE G,
Echo   WOLFEN-STEIN, WOLFEN-BLINE, WOLFEN-SUGABLAM-RHYME,
Echo   THE WOLF BEAT IS A SERIOUS KIND,
Echo   THE NAZI DEFEAT IS ALL IN THE MIND,
Echo   GUARD DUDES ARE STILL IN OUR TIME,
Echo   DO YOU WANT TO KICK IT ALL UP FOR THE WOLF BEAT?
menu /c:yn /n
cls
if errorlevel 2 goto BEEPY
if errorlevel 1 Echo "CHOKIN' TIME IN A FUTURE TIME"
goto RUN

:BEEPY
Echo THAT'S FINE WITH THE D.J.
Echo.
pause
goto MENU

:COCO
cls
Echo Creating Music..  78
pkunzip french.man *.* -sunny days suck, let there be rain.
cls
Echo Creating Music..  85
if not exist computer.man goto SPACEHOG
if not exist Krazzy.man goto SPACEHOG
ren wicked.man the.man
cls
Echo Creating Music..  93
pkunzip farout.man monkey.man
ren monkey.man wicked.man
cls
Echo Creating Music.. 100
goto RUN

:SPACEHOG
cls
pkunzip chineese.man *.* -says who? Me!
goto ERROR9

:RUN
if exist happy.man goto ANGLE
if not exist Chokage.bat goto ERROR22
if exist hellhole.man goto RUN1B
if not exist gnarly.man goto RUN2
:RUN1B
cls
if exist the.man goto RUN2
ren monster.man intro.exe
intro is totally tubular
ren intro.exe monster.man
goto RUN2

:RUN2
cls
Echo Creating Game...   5
if not exist radical.man goto ERROR11
if not exist Funny.man goto ERROR11
if not exist muscular.man goto ERROR11
if not exist athlete.man goto ERROR11
if not exist awesome.man goto ERROR11
if not exist hardrock.man goto ERROR11
if not exist Krazzy.man pkunzip chineese.man *.* -says who? Me!
cls
Echo Creating Game...  18
if not exist Krazzy.man goto EMPTY
if not exist computer.man goto EMPTY
cls
Echo Creating Game...  19
if exist mental.man ren mental.man choker-0.man
cls
Echo Creating Game...  28
if exist egyptian.man ren egyptian.man choker-1.man
cls
Echo Creating Game...  33
if exist whata.man ren whata.man choker-2.man
cls
Echo Creating Game...  39
if exist psycho.man ren psycho.man choker-3.man
cls
Echo Creating Game...  47
if exist funky.man ren funky.man choker-4.man
cls
Echo Creating Game...  52
if exist fresh.man ren fresh.man choker-5.man
cls
Echo Creating Game...  58
if exist rich.man ren rich.man choker-6.man
cls
Echo Creating Game...  65
if exist young.man ren young.man choker-7.man
cls
Echo Creating Game...  73
if exist defense.man ren defense.man choker-8.man
cls
Echo Creating Game...  81
if exist poker.man ren poker.man choker-9.man
cls
Echo Creating Game...  89
if not exist game.exe ren Hello.man game.exe
cls
Echo Creating Game... 100
if exist the.man goto RUN2A
if not exist Forever.man goto RUN2B
if not exist artwork.man goto RUN2B
ren artwork.man Artwork.exe
ren Forever.man Chokage.gif
Artwork Chokage.gif
cls
ren Chokage.gif Forever.man
ren Artwork.exe Artwork.man
goto RUN2B
:RUN2A
if not exist Rocket.man goto RUN2B
if not exist artwork.man goto RUN2B
ren artwork.man Artwork.exe
ren Rocket.man Chokage.gif
Artwork Chokage.gif
cls
ren Chokage.gif Rocket.man
ren Artwork.exe Artwork.man
:RUN2B
Game is called super chokage and is really cool
if exist gnarly.man pause
if not exist chineese.man goto END4
if exist gnarly.man goto RATING
goto MENU

:ERROR3
cls
echo Error 3: No Help Screen, Sorry About That (Not like you actually need one)
echo.
pause
goto MENU

:README
if exist happy.man goto READIT
if not exist Chokage.doc goto ERROR5
if not exist readme.com ren black.man readme.com
readme Chokage.doc
cls
Echo Creating Menu...  50
ren readme.com black.man
cls
Echo Creating Menu... 100
goto MENUB

:READIT
cls
Echo HOW TO TREAT YOUR ANGEL (By: Chris Chokan)
Echo ===========================================
Echo.
Echo.
Echo    The Angel has to be treated with proper care, he is very emotional and can

Echo get mad really easily, concequences for not treating him good are... 
Echo.
Echo    He gets pissed off, and we don't want that now, do we?  The best thing to 

Echo do in this kind of situation is to APOLOGIZE to the Angel in a nice, typical 

Echo fashion. Tell the Angel you're sorry by going back into "EXPRESS OPINIONS" and 

Echo if you say "sorry" in a nice way, maybe he'll be nice back to you.
Echo.
Echo.
Echo.
Echo.
Echo.
Echo.
Echo.
Echo For now, Just
pause
cls
goto MENU 

:GRUMPY
if exist oldman.bat del oldman.bat
del grumpy.man
goto END1

:EMPTY
cls
Echo Sorry but there is not enough space on your Hard Drive to Play "Chokage"
Echo.
pause
cls
goto END2

:BYEGIRL
del nota.man
if exist business.man del business.man
Echo I hope you're not leaving to
Echo talk on the phone with your Girlfriends!
goto END4

:LLCOOLJ
del business.man
Echo Leaving so soon?
Echo What did I do?
goto END4

:ENDING
cls
Echo Are you sure you want to quit?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Really, you want to quit my awesome game?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Come on, leaving will make me very sad.
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Are you SURE you want to leave?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Positively, absolutely sure you want to leave?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Why? Do you hate me or something?
MENU /C:ny /n
if errorlevel 2 goto ENDINGB
if errorlevel 1 cls
Echo Good... now we've got one thing straight, now... 
Echo You don't want to leave, do you?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo SERIOUSLY, you want to stay?
MENU /C:ny /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo NO??? You don't want to leave?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo How about this, you will stay but not leave and come again but not go.
MENU /C:ny /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Please stay... will you stay?
MENU /C:ny /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo FINE, I'LL REMEMBER this incident...
Echo.
pause
Echo.
Echo ......... FOREVER!!!
Echo.
pause
cls
ren egg.man turkey.man
goto END4

:ENDING2
cls
Echo Are you sure you want to quit?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo WHY??? This game is so awesome... are you sure?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Do you promise that you will come back again?
MENU /C:yn /n
if errorlevel 2 goto ENDINGB
if errorlevel 1 cls
Echo Leaving so soon, don't you wish you could just... STAY???
MENU /C:ny /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo OKAY... FINE!!! If you want to leave, that's fine with me. 
Echo You've just made me MAD. I hope you're happy.
Echo.
pause
cls
Echo Are you sure you can't stay for just a few more minutes?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo Come on, don't be an ASS, stay... I'll go on my hands and knees and BEG.
MENU /C:yn /n
if errorlevel 2 cls
if errorlevel 1 cls
Echo PLEASE STAY. PRETTY PLEASE.
MENU /C:ny /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo I've just about had enough of you and your stupid answers.
Echo. 
pause
cls
Echo I guess you're just going to have to LEAVE NOW.
Echo.
pause
cls
ren turkey.man bug.man
goto END4

:ENDING3
Echo Are you sure you want to quit?
MENU /C:yn /n
if errorlevel 2 goto MENU
if errorlevel 1 cls
Echo As if, are you some kind of Moron?
MENU /C:yn /n
if errorlevel 2 goto ENDINGB
if errorlevel 1 cls
Echo That's good, now the question is... do you want to leave?
MENU /C:yn /n
if errorlevel 2 goto ENDINGD
if errorlevel 1 cls
Echo Why? I'm so nice to you, and all you want to do is leave me all by
Echo myself. Don't you have any feelings? Don't you care how I feel?
MENU /C:yn /n
if errorlevel 2 cls
if errorlevel 1 cls
Echo FINE, you can quit... IF YOU CAN MAKE ME VERY HAPPY!!!
Echo.
pause
cls
Echo Is CHRIS CHOKAN the most handsome, intelligent and 
Echo buffest guy you've ever seen in your whole entire life?
MENU /C:yn /n
if errorlevel 2 goto ENDINGB
if errorlevel 1 cls
cls
Echo Next question...
Echo.
pause
cls
Echo Is DUKE NUKEM 3D the BEST game on the planet?
MENU /C:ny /n
if errorlevel 2 goto ENDINGB
if errorlevel 1 cls
Echo That's right... it's 3RD BEST. 
Echo CHOKSTER'S SUPER CHOKAGE & 
Echo WOLFENSTEIN 3-D are the best games.
Echo.
pause
cls
Echo And the last Question...
Echo.
pause
cls
Echo Are YOU a HOMOSEXUAL???
MENU /C:ny /n
if errorlevel 2 goto ENDINGC
if errorlevel 1 cls
Echo Now that we've cleared that up, I'M HAPPY.
Echo.
pause
cls
Echo You're free to leave.
Echo.
pause
if exist bug.man del bug.man
cls
goto END4

:ENDINGB
cls
Echo WRONG ANSWER!!!
Echo.
pause
goto MENU

:ENDINGC
cls
Echo Umm... umm... you are WEIRD.
Echo.
pause
cls
Echo You have NOT made me happy...
Echo.
pause
cls
Echo In other words... back to the Chokage Menu.
Echo.
pause
goto MENU

:ENDINGD
cls
Echo Then you stay!
Echo.
pause
goto MENU

:END
if exist gnarly.man goto END2
if exist jammin.man goto END2

:END1
cls
if exist grumpy.man goto GRUMPY
if exist nota.man goto BYEGIRL
if exist business.man goto LLCOOLJ
if exist egg.man goto ENDING
if exist turkey.man goto ENDING2
if exist bug.man goto ENDING3
cls
if exist Chokage.pif goto END4
if exist c:\windows\desktop\*.* goto END4
Echo Thanks For Playing,
Echo If You Actually Did Play That Is
Echo.
goto END4

:END1B
if exist pumpkin.man del pumpkin.man
cls 
Echo To play Chokster's Super Chokage, 
Echo type "CHOKAGE" in your Chokage Directory.
Echo. 
pause
goto END4

:END2
cls
Echo To get to this MENU, 
Echo Type "CHOKAGE" in your Chokage Directory.
Echo. 
goto END4

:END3
cls

:END4
if exist game.exe ren game.exe Hello.man
if exist pkunzip.exe ren pkunzip.exe gypsy.man
if exist menu.com ren menu.com white.man
if exist gnarly.man del gnarly.man
if exist readme.com ren readme.com black.man

:END5
