cls
 (at) echo off
:message
echo             ESCAPE FROM WOLFENSTIEN 2
echo Levels by Cyber Grunger (Jesse) Built in 1995 This file
echo is not backed by Id, or Appogee! Dont ask for assistace from
echo them.     ......... THEY WONT HELP!!!!! .......
pause
echo Hey, thanks for taking the time to download this
echo file.These levels are all original* this file will tell
echo what to do and the story and stuff.
echo *except for level 5 which is from SOD with a few minor
echo changes........
pause           
cls
echo                        MANUAL
pause
echo                      ...ThE sToRy...
echo B.J. (you) escapes from castle "Wolfenstien" He remembers the
echo main reason he went... to investigate the rumors that Dr. Schabbs
echo has been doing expiraments on humans... Then our forgetful hero
echo remembers that he saw the plans while being hauled off to the prison
echo The plans of human tests and how they would work! He also thought
echo he remembered seeing a 3 armed guy with a skin problem in green
echo pajamas hiding in the shadows of the prison.So you know what B.J. 
echo dose? he marches right back in and starts looking for those plans.
echo All he knows is that they are in the east wing of the castle not
echo in the west wing that he escaped from. He finds a weak spot in the 
echo nazi's defences and blows away the one guard on duty finds the
echo secret door in and then......and then.....
pause
cls
echo AND THEN!!!!.................
pause
cls
echo thats where your mission begins...
pause
cls
echo to move press the arow bars
echo to shoot press controll 
echo to open doors press space bars
echo those are the basic control buttons
pause
cls
echo .....Other add-on levels I've built.....
pause
echo The UAC Missions
echo Spear Of Destiny 2
echo Beer of destiny
echo Hitler's Revenge
echo (None of these are available on-line as of Dec.4.1995
echo I plan to up-load some of these.
pause
echo thanks again for down-loading this file...
echo have fun!
pause
echo ========================================================================
echo                              LATER!
echo=========================================================================

