 (at) ECHO OFF
:origin
CLS
echo ∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫
echo ∫∫€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€∫∫

echo ∫∫€ €€€ﬂﬂﬂﬂ€€€ €€€ﬂﬂﬂﬂ€€€ €€€ﬂﬂﬂﬂﬂ €€€ﬂﬂﬂﬂﬂ ﬂﬂﬂ€€€ﬂﬂﬂ €€€ﬂﬂﬂﬂﬂ €€€ €€‹‹  €€ €∞∞

echo ∫∫€ €€€ﬂﬂﬂﬂﬂﬂﬂ €€€ﬂﬂﬂﬂ€€€ €€€      ﬂﬂﬂﬂﬂ€€€    €€€    €€€ﬂﬂﬂﬂﬂ €€€ €€ ﬂ€‹€€ €∞∞

echo ∫∫€ €€€        €€€    €€€ €€€‹‹‹‹‹ ‹‹‹‹‹€€€    €€€    €€€‹‹‹‹‹ €€€ €€   ﬂ€€ €∞∞

echo ∫≤€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€∞∞

echo ≤≤≤≤∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ CHOOSE: (1) Pacstein 1    (B) Pacstein 11                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (2) Pacstein 2    (C) Pacstein 12                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (3) Pacstein 3    (D) Pacstein 13                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (4) Pacstein 4    (E) Pacstein 14                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (5) Pacstein 5    (F) Pacstein 15                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (6) Pacstein 6    (G) Pacstein 16                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (7) Pacstein 7    (H) Pacstein 17                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (8) Pacstein 8    (I) Pacstein 18                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (9) Pacstein 9    (J) Pacspear                     ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (A) Pacstein 10   (Q) Quit                         ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
choice /c:123456789ABCDEFGHIJQ /N /T:Q,90
if errorlevel 20 goto :end
if errorlevel 19 goto :19
if errorlevel 18 goto :18
if errorlevel 17 goto :17
if errorlevel 16 goto :16
if errorlevel 15 goto :15
if errorlevel 14 goto :14
if errorlevel 13 goto :13
if errorlevel 12 goto :twelve
if errorlevel 11 goto :eleven
if errorlevel 10 goto :ten
if errorlevel 9 goto :nine
if errorlevel 8 goto :eight
if errorlevel 7 goto :seven
if errorlevel 6 goto :six
if errorlevel 5 goto :five
if errorlevel 4 goto :four
if errorlevel 3 goto :three
if errorlevel 2 goto :two
if errorlevel 1 goto :one
if errorlevel 0 goto :origin

:one
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r7 maphead.wl1
copy games\gamemaps.r7 gamemaps.wl1
copy games\vgadict.ps1 vgadict.wl1
copy games\vgagraph.ps1 vgagraph.wl1
copy games\vgahead.ps1 vgahead.wl1
call go.bat
goto :origin

:two
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.wd2 maphead.wl1
copy games\gamemaps.wd2 gamemaps.wl1
copy games\vgadict.ps2 vgadict.wl1
copy games\vgagraph.ps2 vgagraph.wl1
copy games\vgahead.ps2 vgahead.wl1
call go.bat
goto :origin

:three
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r1 maphead.wl1
copy games\gamemaps.r1 gamemaps.wl1
copy games\vgadict.ps3 vgadict.wl1
copy games\vgagraph.ps3 vgagraph.wl1
copy games\vgahead.ps3 vgahead.wl1
call go.bat
goto :origin

:four
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r2 maphead.wl1
copy games\gamemaps.r2 gamemaps.wl1
copy games\vgadict.ps4 vgadict.wl1
copy games\vgagraph.ps4 vgagraph.wl1
copy games\vgahead.ps4 vgahead.wl1
call go.bat
goto :origin

:five
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r3 maphead.wl1
copy games\gamemaps.r3 gamemaps.wl1
copy games\vgadict.ps5 vgadict.wl1
copy games\vgagraph.ps5 vgagraph.wl1
copy games\vgahead.ps5 vgahead.wl1
call go.bat
goto :origin

:six
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r4 maphead.wl1
copy games\gamemaps.r4 gamemaps.wl1
copy games\vgadict.ps6 vgadict.wl1
copy games\vgagraph.ps6 vgagraph.wl1
copy games\vgahead.ps6 vgahead.wl1
call go.bat
goto :origin

:seven
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r5 maphead.wl1
copy games\gamemaps.r5 gamemaps.wl1
copy games\vgadict.ps7 vgadict.wl1
copy games\vgagraph.ps7 vgagraph.wl1
copy games\vgahead.ps7 vgahead.wl1
call go.bat
goto :origin

:eight
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r6 maphead.wl1
copy games\gamemaps.r6 gamemaps.wl1
copy games\vgadict.ps8 vgadict.wl1
copy games\vgagraph.ps8 vgagraph.wl1
copy games\vgahead.ps8 vgahead.wl1
call go.bat
goto :origin

:nine
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.r8 maphead.wl1
copy games\gamemaps.r8 gamemaps.wl1
copy games\vgadict.ps9 vgadict.wl1
copy games\vgagraph.ps9 vgagraph.wl1
copy games\vgahead.ps9 vgahead.wl1
call go.bat
goto :origin

:ten
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.rg1 maphead.wl1
copy games\gamemaps.rg1 gamemaps.wl1
copy games\vgadict.p10 vgadict.wl1
copy games\vgagraph.p10 vgagraph.wl1
copy games\vgahead.p10 vgahead.wl1
call go.bat
goto :origin

:eleven
 (at) echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.rg2 maphead.wl1
copy games\gamemaps.rg2 gamemaps.wl1
copy games\vgadict.p11 vgadict.wl1
copy games\vgagraph.p11 vgagraph.wl1
copy games\vgahead.p11 vgahead.wl1
call go.bat
goto :origin

:twelve
 (at) echo off
copy games\vswap.wol vswap.wl1
copy games\maphead.p2 maphead.wl1
copy games\gamemaps.p2 gamemaps.wl1
copy games\vgadict.p12 vgadict.wl1
copy games\vgagraph.p12 vgagraph.wl1
copy games\vgahead.p12 vgahead.wl1
call go.bat
goto :origin

:13
 (at) echo off
copy games\maphead.bla maphead.wl1
copy games\gamemaps.bla gamemaps.wl1
copy games\vgadict.bla vgadict.wl1
copy games\vgagraph.bla vgagraph.wl1
copy games\vgahead.bla vgahead.wl1
call go.bat
goto :origin

:14
 (at) echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.r14 maphead.wl1
copy games\gamemaps.r14 gamemaps.wl1
copy games\vgadict.r14 vgadict.wl1
copy games\vgagraph.r14 vgagraph.wl1
copy games\vgahead.r14 vgahead.wl1
call go2.bat
goto :origin

:15
 (at) echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.cov maphead.wl1
copy games\gamemaps.cov gamemaps.wl1
copy games\vgadict.cov vgadict.wl1
copy games\vgagraph.cov vgagraph.wl1
copy games\vgahead.cov vgahead.wl1
call go2.bat
goto :origin

:16
 (at) echo off
copy games\maphead.16 maphead.wl1
copy games\gamemaps.16 gamemaps.wl1
copy games\vgadict.16 vgadict.wl1
copy games\vgagraph.16 vgagraph.wl1
copy games\vgahead.16 vgahead.wl1
call go.bat
goto :origin

:17
 (at) echo off
copy games\maphead.17 maphead.wl1
copy games\gamemaps.17 gamemaps.wl1
copy games\vgadict.17 vgadict.wl1
copy games\vgagraph.17 vgagraph.wl1
copy games\vgahead.17 vgahead.wl1
call go.bat
goto :origin

:18
 (at) echo off
copy games\maphead.mus maphead.wl1
copy games\gamemaps.mus gamemaps.wl1
copy games\vgadict.18 vgadict.wl1
copy games\vgagraph.18 vgagraph.wl1
copy games\vgahead.18 vgahead.wl1
call go.bat
goto :origin

:19
 (at) echo off
 (at) call Pacspear.bat
goto :origin

:end
