^P
^C2d Pacspear 2
^G40,16,16


^C2bYou are Captain Zoom, secret army agent, who has become trapped in a faraway 
land, filled with formidable adversaries who are quick-striking and intelligent. 
You must fight your way to escape. It won't be easy as you venture through level 
after level of complex situations. Good luck in your adventure! Create your own story 
as you go along!

^P
^C2d Pacspear 2 - Credits
^G40,16,78
^C2b This game is a mod by Gary Acord of id's Spear Of Destiny. The exe file was 
compiled by AReyeP/MCS Amsterdam. Additional graphics-Mr. Choi. Help and advice creating 
and distributing this game-Brian Lowe.

^C2bI used Floedit, Mapedit 7.2 and 8.4, Bill Kirby's Wolfedit, ChaosEdit, Varsity, 
Deluxe Animation, and Paintbrush to create Pacspear 2.

^P
^C2d Pacspear 2 - Conclusion
^G40,16,31

^C2bThanks for playing Pacspear 2. If you wish to comment on the game feel free to 
drop me an email.

^C2dGary Acord
^C2bAcordgames (at) juno.com

^C2dAcord Games Website is:
^C2bhttp://Acordgames.webstarts.com

^P
^G0,0,83

^E
