^P
^C24 PACSPEAR 2

^G32,16,31
^C00 Thanks for playing Pacspear 2! Congratulations! You've won! Killing Zapper who 
threw the snowballs was the key to victory!
^C00If you wish to comment on the game feel to email me at ^C2bAcordgames@juno.com


^C2dAcord Games Website is:
^C2bhttp://Acordgames.webstarts.com

^P
^C2d PACSPEAR 2 - Credits
^G40,16,78
^C2b This game is a mod by Gary Acord of id's Spear Of Destiny. The exe file was 
compiled by AReyeP/MCS Amsterdam. Additional graphics-Mr. Choi. Help and advice creating 
and distributing this game-Brian Lowe.

^C2bI used Floedit, Mapedit 7.2 and 8.4, Bill Kirby's Wolfedit, ChaosEdit, Varsity, 
Deluxe Animation, and Paintbrush to create Pacspear 2.

^P
^G0,0,92

^E
