@ECHO OFF
@call TITLE.EXE
:origin
CLS
echo ККлппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппплКК

echo ККл ллпппплл ллппплл ллпллплл ллппплл лл  лл ллпппп ппллпп ллпппп лл лл  лл лАА

echo ККл ллпплппп лл   лл лл лл лл ллппплл лллмлл пппплл   лл   ллпппп лл лллмлл лАА

echo ККл лл  лммм ллмммлл лл лл лл лл   лл лл плл ммммлл   лл   ллмммм лл лл плл лАА

echo ККл                                                                         лАА

echo ККл  ллпппплл ллппппп лл   лл пллп ллппппп пллп пппллппп ллппппп пллпппплл  лАА

echo ККл  ллпплппп ллппппп плл ллп  лл  ппппплл  лл     лл    ллппппп  лл    лл  лАА

echo ККл  лл  лммм ллммммм  плллп  мллм мммммлл мллм    лл    ллммммм мллммммлл  лАА

echo ККлмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммлАА

echo КККААААААЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭАААААААААА
echo КлКАБВлБА CHOOSE: (1) Game 1     (C) Game 12                         АБВлВБАКлА
echo КлКАБВлБА         (2) Game 2     (D) Game 13                         АБВлВБАКлА
echo КлКАБВлБА         (3) Game 3     (E) Game 14                         АБВлВБАКлА
echo КлКАБВлБА         (4) Game 4     (F) Game 15                         АБВлВБАКлА
echo КлКАБВлБА         (5) Game 5     (G) Game 16                         АБВлВБАКлА
echo КлКАБВлБА         (6) Game 6     (H) Game 17                         АБВлВБАКлА
echo КлКАБВлБА         (7) Game 7     (I) Game 18                         АБВлВБАКлА
echo КлКАБВлБА         (8) Game 8     (J) Game 19                         АБВлВБАКлА
echo КлКАБВлБА         (9) Game 9     (K) Game 20                         АБВлВБАКлА
echo КлКАБВлБА         (A) Game 10    (L) Game 21                         АБВлВБАКлА
echo КлКАБВлБА         (B) Game 11    (M) Game 22                (Q) Quit АБВлВБАКлА
echo КлКАБВлБАЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭАБВлВБАКлА
echo КлКАБВлллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллВБАКлА
choice /c:123456789ABCDEFGHIJKLMQ /N /T:Q,90
if errorlevel 23 goto :end
if errorlevel 22 goto :22
if errorlevel 21 goto :21
if errorlevel 20 goto :20
if errorlevel 19 goto :19
if errorlevel 18 goto :18
if errorlevel 17 goto :17
if errorlevel 16 goto :16
if errorlevel 15 goto :15
if errorlevel 14 goto :14
if errorlevel 13 goto :13
if errorlevel 12 goto :12
if errorlevel 11 goto :11
if errorlevel 10 goto :10
if errorlevel 9 goto :9
if errorlevel 8 goto :8
if errorlevel 7 goto :7
if errorlevel 6 goto :6
if errorlevel 5 goto :5
if errorlevel 4 goto :4
if errorlevel 3 goto :3
if errorlevel 2 goto :2
if errorlevel 1 goto :1
if errorlevel 0 goto :origin

:1
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r1 maphead.wl1
copy games\gamemaps.r1 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:2
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r2 maphead.wl1
copy games\gamemaps.r2 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:3
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r3 maphead.wl1
copy games\gamemaps.r3 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:4
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r4 maphead.wl1
copy games\gamemaps.r4 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:5
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r5 maphead.wl1
copy games\gamemaps.r5 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:6
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r6 maphead.wl1
copy games\gamemaps.r6 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:7
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.r7 maphead.wl1
copy games\gamemaps.r7 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:8
@echo off
copy games\vswap.r8 vswap.wl1
copy games\maphead.r8 maphead.wl1
copy games\gamemaps.r8 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:9
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.p2 maphead.wl1
copy games\gamemaps.p2 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:10
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.wd2 maphead.wl1
copy games\gamemaps.wd2 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:11
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.cod maphead.wl1
copy games\gamemaps.cod gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:12
@echo off
copy games\vswap.rg1 vswap.wl1
copy games\maphead.rg1 maphead.wl1
copy games\gamemaps.rg1 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:13
@echo off
copy games\vswap.rg2 vswap.wl1
copy games\maphead.rg2 maphead.wl1
copy games\gamemaps.rg2 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:14
@echo off
copy games\vswap.rg3 vswap.wl1
copy games\maphead.rg3 maphead.wl1
copy games\gamemaps.rg3 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:15
@echo off
copy games\vswap.xms vswap.wl1
copy games\maphead.xms maphead.wl1
copy games\gamemaps.xms gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:16
@echo off
copy games\vswap.xms vswap.wl1
copy games\maphead.xm2 maphead.wl1
copy games\gamemaps.xm2 gamemaps.wl1
copy sexstein.exe engine.exe
goto :go

:17
@echo off
copy games\maphead.wd1 maphead.wl1
copy games\gamemaps.wd1 gamemaps.wl1
copy dosplay.exe engine.exe
goto :go

:18
@echo off
copy games\gamemaps.bla gamemaps.wl1
copy games\maphead.bla maphead.wl1
copy dosplay.exe engine.exe
goto :go

:19
@echo off
copy games\gamemaps.mus gamemaps.wl1
copy games\maphead.mus maphead.wl1
copy dosplay.exe engine.exe
goto :go

:20
@echo off
copy games\gamemaps.17 gamemaps.wl1
copy games\maphead.17 maphead.wl1
copy dosplay.exe engine.exe
goto :go

:21
@echo off
copy games\gamemaps.18 gamemaps.wl1
copy games\maphead.18 maphead.wl1
copy dosplay.exe engine.exe
goto :go

:22
@echo off
copy games\gamemaps.PS1 gamemaps.wl1
copy games\maphead.PS1 maphead.wl1
copy dosplay.exe engine.exe
goto :go

:go
CLS
echo ККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККККК
echo ККлппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппплКК

echo ККл ллпппплл ллппплл ллпллплл ллппплл лл  лл ллпппп ппллпп ллпппп лл лл  лл лАА

echo ККл ллпплппп лл   лл лл лл лл ллппплл лллмлл пппплл   лл   ллпппп лл лллмлл лАА

echo ККл лл  лммм ллмммлл лл лл лл лл   лл лл плл ммммлл   лл   ллмммм лл лл плл лАА

echo ККл                                                                         лАА

echo ККл  ллпппплл ллппппп лл   лл пллп ллппппп пллп пппллппп ллппппп пллпппплл  лАА

echo ККл  ллпплппп ллппппп плл ллп  лл  ппппплл  лл     лл    ллппппп  лл    лл  лАА

echo ККл  лл  лммм ллммммм  плллп  мллм мммммлл мллм    лл    ллммммм мллммммлл  лАА

echo КВлмммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммлАА

echo КлКАБВлБАЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭАБВлВБАКлА
echo КлКАБВлБА CHOOSE: (1) DOS Play                                       АБВлВБАКлА
echo КлКАБВлБА         (2) WIN Play                                       АБВлВБАКлА
echo КлКАБВлБА         (3) GL Play                                        АБВлВБАКлА
echo КлКАБВлБА         (Q) Quit                                           АБВлВБАКлА
echo КлКАБВлБАЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭАБВлВБАКлА
echo КлКАБВлллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллВБАКлА
choice /c:123Q /N /T:Q,90
if errorlevel 4 goto :origin
if errorlevel 3 goto :3
if errorlevel 2 goto :2
if errorlevel 1 goto :1
if errorlevel 0 goto :000

:1
@cls
@CALL Engine.exe
goto :origin

:2
@cls
@call winplay.exe
goto :origin

:3
@cls
@call glplay.exe
goto :origin

:end
