@ECHO OFF
@call TITLE.EXE
:origin
CLS
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∫
echo ∫€∫∞±≤€≤±∞  ‹‹ ‹ ‹‹ ‹‹‹‹‹‹ ‹‹    ‹‹‹‹‹ ‹‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹‹‹‹ ‹‹‹‹‹  ∞±≤€≤±∞∫€∫
echo ∫€∫∞±≤€≤±∞  €€ € €€ €€  €€ €€    €€    €€ € €€ €€  €€  €€  €€ €€ ﬂﬂ  ∞±≤€≤±∞∫€∫
echo ∫€∫∞±≤€≤±∞  €€ € €€ €€  €€ €€    €€‹‹‹ €€ € €€ €€  €€  €€  €€ €€‹‹‹  ∞±≤€≤±∞∫€∫
echo ∫€∫∞±≤€≤±∞  €€ € €€ €€  €€ €€    €€    €€ € €€ €€  €€  €€  €€    €€  ∞±≤€≤±∞∫€∫
echo ∫€∫∞±≤€≤±∞  €€‹€‹€€ €€‹‹€€ €€‹‹‹ €€    €€ € €€ €€‹‹€€ ‹€€‹‹€€ €€‹€€  ∞±≤€≤±∞∫€∫
echo ∫€∫∞±≤€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€≤±∞∫€∫
echo ∫€∫∞±∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∫€∫
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ CHOOSE: (1) Game 1     (C) Game 12    (U) Play Wolfenstein ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (2) Game 2     (D) Game 13    (V) Play Doomstein   ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (3) Game 3     (E) Game 14    (W) Play Pacstein    ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (4) Game 4     (F) Game 15    (X) Play Pacstein II ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (5) Game 5     (G) Game 16    (Y) Play Romanstein  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (6) Game 6     (H) Game 17    (Z) Play Blakestein  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (7) Game 7     (I) Game 18                         ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (8) Game 8     (J) Game 19                         ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (9) Game 9     (K) Game 20                         ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (A) Game 10    (L) Game 21                         ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (B) Game 11    (M) Game 22                (Q) Quit ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
choice /c:123456789ABCDEFGHIJKLMUVWXYZQ /N /T:Q,90
if errorlevel 29 goto :end
if errorlevel 28 goto :28
if errorlevel 27 goto :27
if errorlevel 26 goto :26
if errorlevel 25 goto :25
if errorlevel 24 goto :24
if errorlevel 23 goto :23
if errorlevel 22 goto :22
if errorlevel 21 goto :21
if errorlevel 20 goto :20
if errorlevel 19 goto :19
if errorlevel 18 goto :18
if errorlevel 17 goto :17
if errorlevel 16 goto :16
if errorlevel 15 goto :fift
if errorlevel 14 goto :fourt
if errorlevel 13 goto :thirt
if errorlevel 12 goto :twelve
if errorlevel 11 goto :eleven
if errorlevel 10 goto :ten
if errorlevel 9 goto :nine
if errorlevel 8 goto :eight
if errorlevel 7 goto :seven
if errorlevel 6 goto :six
if errorlevel 5 goto :five
if errorlevel 4 goto :four
if errorlevel 3 goto :three
if errorlevel 2 goto :two
if errorlevel 1 goto :one
if errorlevel 0 goto :origin

:one
@echo off
copy games\maphead.r7 maphead.wl1
copy games\gamemaps.r7 gamemaps.wl1
call go.bat
goto :origin

:two
@echo off
copy games\maphead.wd2 maphead.wl1
copy games\gamemaps.wd2 gamemaps.wl1
call go.bat
goto :origin

:three
@echo off
copy games\maphead.r1 maphead.wl1
copy games\gamemaps.r1 gamemaps.wl1
call go.bat
goto :origin

:four
@echo off
copy games\maphead.r2 maphead.wl1
copy games\gamemaps.r2 gamemaps.wl1
call go.bat
goto :origin

:five
@echo off
copy games\maphead.r3 maphead.wl1
copy games\gamemaps.r3 gamemaps.wl1
call go.bat
goto :origin

:six
@echo off
copy games\maphead.r4 maphead.wl1
copy games\gamemaps.r4 gamemaps.wl1
call go.bat
goto :origin

:seven
@echo off
copy games\maphead.r5 maphead.wl1
copy games\gamemaps.r5 gamemaps.wl1
call go.bat
goto :origin

:eight
@echo off
copy games\maphead.r6 maphead.wl1
copy games\gamemaps.r6 gamemaps.wl1
call go.bat
goto :origin

:nine
@echo off
copy games\maphead.r8 maphead.wl1
copy games\gamemaps.r8 gamemaps.wl1
call go.bat
goto :origin

:ten
@echo off
copy games\maphead.rg1 maphead.wl1
copy games\gamemaps.rg1 gamemaps.wl1
call go.bat
goto :origin

:eleven
@echo off
copy games\maphead.rg2 maphead.wl1
copy games\gamemaps.rg2 gamemaps.wl1
call go.bat
goto :origin

:twelve
@echo off
copy games\maphead.wol maphead.wl1
copy games\gamemaps.wol gamemaps.wl1
call go.bat
goto :origin

:thirt
@echo off
copy games\gamemaps.bla gamemaps.wl1
copy games\maphead.bla maphead.wl1
call go.bat
goto :origin

:fourt
@echo off
copy games\gamemaps.r14 gamemaps.wl1
copy games\maphead.r14 maphead.wl1
call go2.bat
goto :origin

:fift
@echo off
copy games\gamemaps.cov gamemaps.wl1
copy games\maphead.cov maphead.wl1
call go.bat
goto :origin

:16
@echo off
copy games\gamemaps.mus gamemaps.wl1
copy games\maphead.mus maphead.wl1
call go.bat
goto :origin

:17
@echo off
copy games\gamemaps.17 gamemaps.wl1
copy games\maphead.17 maphead.wl1
call go.bat
goto :origin

:18
@echo off
copy games\gamemaps.18 gamemaps.wl1
copy games\maphead.18 maphead.wl1
call go.bat
goto :origin

:19
@echo off
copy games\gamemaps.wd1 gamemaps.wl1
copy games\maphead.wd1 maphead.wl1
call go.bat
goto :origin

:20
@echo off
copy games\gamemaps.ps1 gamemaps.wl1
copy games\maphead.ps1 maphead.wl1
call go.bat
goto :origin

:21
@echo off
copy games\gamemaps.tu2 gamemaps.wl1
copy games\maphead.tu2 maphead.wl1
call go.bat
goto :origin

:22
@echo off
copy games\gamemaps.rg3 gamemaps.wl1
copy games\maphead.rg3 maphead.wl1
call go.bat
goto :origin

:23
@echo off
copy games\vgadict.wol vgadict.wl1
copy games\vgahead.wol vgahead.wl1
copy games\vgagraph.wol vgagraph.wl1
copy games\vswap.wol vswap.wl1
goto :origin

:24
@echo off
copy games\vgadict.doo vgadict.wl1
copy games\vgahead.doo vgahead.wl1
copy games\vgagraph.doo vgagraph.wl1
copy games\vswap.doo vswap.wl1
goto :origin

:25
@echo off
copy games\vgadict.pac vgadict.wl1
copy games\vgahead.pac vgahead.wl1
copy games\vgagraph.pac vgagraph.wl1
goto :PACSTN

:26
@echo off
copy games\vgadict.enh vgadict.wl1
copy games\vgahead.enh vgahead.wl1
copy games\vgagraph.enh vgagraph.wl1
copy games\vswap.enh vswap.wl1
copy games\config.enh config.wl1
goto :start

:27
@echo off
copy games\vgadict.rom vgadict.wl1
copy games\vgahead.rom vgahead.wl1
copy games\vgagraph.rom vgagraph.wl1
copy games\vswap.rom vswap.wl1
goto :origin

:28
@echo off
copy games\vgadict.bla vgadict.wl1
copy games\vgagraph.bla vgagraph.wl1
copy games\vgahead.bla vgahead.wl1
copy games\vswap.bla vswap.wl1
goto :origin

:start
CLS
echo ∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∫
echo ∫€∫∞±≤€ ‹‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹‹‹ ‹‹‹‹ ‹‹  ‹‹  ‹‹‹‹‹‹‹ €≤±∞∫€∫
echo ∫€∫∞±≤€ €€   €€ €€  €€ €€  €€ €€  ﬂﬂ   €€   €€      €€  €€‹ €€   €€ €€  €≤±∞∫€∫
echo ∫€∫∞±≤€ €€‹‹‹€€ €€‹‹€€ €€     €€‹‹‹‹   €€   €€‹‹‹‹  €€  €€ﬂ€€€   €€ €€  €≤±∞∫€∫
echo ∫€∫∞±≤€ €€      €€  €€ €€         €€   €€   €€      €€  €€ ﬂ€€   €€ €€  €≤±∞∫€∫
echo ∫€∫∞±≤€ €€      €€  €€ €€‹‹€€ €€‹‹€€   €€   €€‹‹‹‹ ‹€€‹ €€  €€  ‹€€‹€€‹ €≤±∞∫€∫
echo ∫€∫∞±≤€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€≤±∞∫€∫
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ CHOOSE: (1) Game 1                (C) Game 12              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (2) Game 2                (D) Game 13              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (3) Game 3                (E) Game 14              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (4) Game 4                (F) Game 15              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (5) Game 5                (G) Game 16              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (6) Game 6                (H) Game 17              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (7) Game 7                (I) Game 18              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (8) Game 8                (J) Game 19              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (9) Game 9                (K) Game 20              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (A) Game 10               (L) Game 21              ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (B) Game 11               (M) Game 22     (Q) Quit ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
choice /c:123456789ABCDEFGHIJKLMQ /N /T:Q,90
if errorlevel 23 goto :psend
if errorlevel 22 goto :ps22
if errorlevel 21 goto :ps21
if errorlevel 20 goto :ps20
if errorlevel 19 goto :ps19
if errorlevel 18 goto :ps18
if errorlevel 17 goto :ps17
if errorlevel 16 goto :ps16
if errorlevel 15 goto :ps15
if errorlevel 14 goto :ps14
if errorlevel 13 goto :ps13
if errorlevel 12 goto :ps12
if errorlevel 11 goto :ps11
if errorlevel 10 goto :ps10
if errorlevel 9 goto :ps9
if errorlevel 8 goto :ps8
if errorlevel 7 goto :ps7
if errorlevel 6 goto :ps6
if errorlevel 5 goto :ps5
if errorlevel 4 goto :ps4
if errorlevel 3 goto :ps3
if errorlevel 2 goto :ps2
if errorlevel 1 goto :ps1
if errorlevel 0 goto :start

:ps1
@echo off
copy games\maphead.r7 maphead.wl1
copy games\gamemaps.r7 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps2
@echo off
copy games\maphead.wd2 maphead.wl1
copy games\gamemaps.wd2 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps3
@echo off
copy games\maphead.r1 maphead.wl1
copy games\gamemaps.r1 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps4
@echo off
copy games\maphead.r2 maphead.wl1
copy games\gamemaps.r2 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps5
@echo off
copy games\maphead.r3 maphead.wl1
copy games\gamemaps.r3 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps6
@echo off
copy games\maphead.r4 maphead.wl1
copy games\gamemaps.r4 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps7
@echo off
copy games\maphead.r5 maphead.wl1
copy games\gamemaps.r5 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps8
@echo off
copy games\gamemaps.enh gamemaps.wl1
copy games\maphead.enh maphead.wl1
call pacstein.exe > nul
goto :start

:ps9
@echo off
copy games\maphead.r8 maphead.wl1
copy games\gamemaps.r8 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps10
@echo off
copy games\maphead.rg1 maphead.wl1
copy games\gamemaps.rg1 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps11
@echo off
copy games\maphead.rg2 maphead.wl1
copy games\gamemaps.rg2 gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps12
@echo off
copy games\maphead.wol maphead.wl1
copy games\gamemaps.wol gamemaps.wl1
call pacstein.exe > nul
goto :start

:ps13
@echo off
copy games\gamemaps.bla gamemaps.wl1
copy games\maphead.bla maphead.wl1
call pacstein.exe > nul
goto :start

:ps14
@echo off
copy games\gamemaps.r14 gamemaps.wl1
copy games\maphead.r14 maphead.wl1
call pacstein.exe > nul
goto :start

:ps15
@echo off
copy games\gamemaps.cov gamemaps.wl1
copy games\maphead.cov maphead.wl1
call pacstein.exe > nul
goto :start

:ps16
copy games\gamemaps.mus gamemaps.wl1
copy games\maphead.mus maphead.wl1
call pacstein.exe > nul
goto :start

:ps17
copy games\gamemaps.17 gamemaps.wl1
copy games\maphead.17 maphead.wl1
call pacstein.exe > nul
goto :start

:ps18
copy games\gamemaps.18 gamemaps.wl1
copy games\maphead.18 maphead.wl1
call pacstein.exe > nul
goto :start

:ps19
copy games\gamemaps.wd1 gamemaps.wl1
copy games\maphead.wd1 maphead.wl1
call pacstein.exe > nul
goto :start

:ps20
@echo off
copy games\gamemaps.ps1 gamemaps.wl1
copy games\maphead.ps1 maphead.wl1
call pacstein.exe > nul
goto :start

:ps21
@echo off
copy games\gamemaps.tu2 gamemaps.wl1
copy games\maphead.tu2 maphead.wl1
call pacstein.exe > nul
goto :start

:ps22
@echo off
copy games\gamemaps.rg3 gamemaps.wl1
copy games\maphead.rg3 maphead.wl1
call pacstein.exe > nul
goto :start

:psend
copy games\vswap.r14 vswap.wl1
copy games\vgadict.pac vgadict.wl1
copy games\vgagraph.pac vgagraph.wl1
copy games\vgahead.pac vgahead.wl1
goto :origin

:PACSTN
CLS
echo ∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫∫
echo ∫∫€ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€∫∫

echo ∫∫€ €€€ﬂﬂﬂﬂ€€€ €€€ﬂﬂﬂﬂ€€€ €€€ﬂﬂﬂﬂﬂ €€€ﬂﬂﬂﬂﬂ ﬂﬂﬂ€€€ﬂﬂﬂ €€€ﬂﬂﬂﬂﬂ €€€ €€‹‹  €€ €∞∞

echo ∫∫€ €€€ﬂﬂﬂﬂﬂﬂﬂ €€€ﬂﬂﬂﬂ€€€ €€€      ﬂﬂﬂﬂﬂ€€€    €€€    €€€ﬂﬂﬂﬂﬂ €€€ €€ ﬂ€‹€€ €∞∞

echo ∫∫€ €€€        €€€    €€€ €€€‹‹‹‹‹ ‹‹‹‹‹€€€    €€€    €€€‹‹‹‹‹ €€€ €€   ﬂ€€ €∞∞

echo ∫≤€‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€∞∞

echo ≤≤≤≤∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ CHOOSE: (1) Pacstein 1    (C) Pacstein 12                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (2) Pacstein 2    (D) Pacstein 13                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (3) Pacstein 3    (E) Pacstein 14                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (4) Pacstein 4    (F) Pacstein 15                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (5) Pacstein 5    (G) Pacstein 16                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (6) Pacstein 6    (H) Pacstein 17                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (7) Pacstein 7    (I) Pacstein 18                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (8) Pacstein 8    (J) Pacstein 19                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (9) Pacstein 9    (K) Pacstein 20                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (A) Pacstein 10   (L) Pacstein 21                  ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞         (B) Pacstein 11   (M) Pacstein 22         (Q) Quit ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€±∞ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ∞±≤€≤±∞∫€∞
echo ∫€∫∞±≤€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€€≤±∞∫€∞
choice /c:123456789ABCDEFGHIJKLMQ /N /T:Q,90
if errorlevel 23 goto :PACEND
if errorlevel 22 goto :PAC22
if errorlevel 21 goto :PAC21
if errorlevel 20 goto :PAC20
if errorlevel 19 goto :PAC19
if errorlevel 18 goto :PAC18
if errorlevel 17 goto :PAC17
if errorlevel 16 goto :PAC16
if errorlevel 15 goto :PAC15
if errorlevel 14 goto :PAC14
if errorlevel 13 goto :PAC13
if errorlevel 12 goto :PAC12
if errorlevel 11 goto :PAC11
if errorlevel 10 goto :PAC10
if errorlevel 9 goto :PAC9
if errorlevel 8 goto :PAC8
if errorlevel 7 goto :PAC7
if errorlevel 6 goto :PAC6
if errorlevel 5 goto :PAC5
if errorlevel 4 goto :PAC4
if errorlevel 3 goto :PAC3
if errorlevel 2 goto :PAC2
if errorlevel 1 goto :PAC1
if errorlevel 0 goto :origin

:PAC1
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r7 maphead.wl1
copy games\gamemaps.r7 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC2
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.wd2 maphead.wl1
copy games\gamemaps.wd2 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC3
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r1 maphead.wl1
copy games\gamemaps.r1 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC4
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r2 maphead.wl1
copy games\gamemaps.r2 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC5
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r3 maphead.wl1
copy games\gamemaps.r3 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC6
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r4 maphead.wl1
copy games\gamemaps.r4 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC7
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r5 maphead.wl1
copy games\gamemaps.r5 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC8
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r6 maphead.wl1
copy games\gamemaps.r6 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC9
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.r8 maphead.wl1
copy games\gamemaps.r8 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC10
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.rg1 maphead.wl1
copy games\gamemaps.rg1 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC11
@echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.rg2 maphead.wl1
copy games\gamemaps.rg2 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC12
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.wol maphead.wl1
copy games\gamemaps.wol gamemaps.wl1
call go.bat
goto :PACSTN

:PAC13
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.bla maphead.wl1
copy games\gamemaps.bla gamemaps.wl1
call go.bat
goto :PACSTN

:PAC14
@echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.r14 maphead.wl1
copy games\gamemaps.r14 gamemaps.wl1
call go2.bat
goto :PACSTN

:PAC15
@echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.cov maphead.wl1
copy games\gamemaps.cov gamemaps.wl1
call go.bat
goto :PACSTN

:PAC16
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.mus maphead.wl1
copy games\gamemaps.mus gamemaps.wl1
call go.bat
goto :PACSTN

:PAC17
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.17 maphead.wl1
copy games\gamemaps.17 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC18
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.18 maphead.wl1
copy games\gamemaps.18 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC19
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.wd1 maphead.wl1
copy games\gamemaps.wd1 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC20
@echo off
copy games\vswap.pac vswap.wl1
copy games\maphead.ps1 maphead.wl1
copy games\gamemaps.ps1 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC21
@echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.tu2 maphead.wl1
copy games\gamemaps.tu2 gamemaps.wl1
call go.bat
goto :PACSTN

:PAC22
@echo off
copy games\vswap.r14 vswap.wl1
copy games\maphead.rg3 maphead.wl1
copy games\gamemaps.rg3 gamemaps.wl1
call go.bat
goto :PACSTN

:PACEND
@echo off
copy games\vswap.R14 vswap.wl1
goto :origin

:end
