^P
^C24 OUTGUNNED!!!

^C00 Expecting to face your next challenge as the elevator door opens to the next 
level, you instead find yourself confronted by at least 30 grinning monsters. Forewarned 
by the carnage you'd wreaked on lower levels, they'd been ready for you.


^P
^G30,16,78

^C00 There are many monsters everywhere and time is short. Time to do what heroes 
do. Pull this off, and it'll go down in history.

^E
