^P
^C00
Resistant

Is a TC of ID Software's orginal game Wolfenstein 3D. It has many new features like 
textured floors/skies, a brand new story (no one) and a completely new atmosphere 
and goal.

^P
^C00
Controls

<F1> - Help
<F2> - Save Game
<F3> - Load Game
<F4> - Sound
<F5> - Mouse
<F6> - Customize Controls
<F7> - End Game
<F8> - Quick Save
<F9> - Quick Load

^P
^C00
Controls

You can customize these keys under 'Control'

Move - Arrow Keys
Strafe - <Alt>
Run - <LShift>
Shoot - <Ctrl>
Open/Use - <Space>

^P
^C00
Controls

Weapon Change:

1 - Knife
2 - Rifle
3 - Machine Gun
4 - Chaingun
5 - Death Cross
(In cheat mode:)
6 - A thing you use to cut plants xD
^P
^C00
Items

Life Essence (heart) - 20 Healthpoints
Blood - 10 Healthpoints
Clip - 4 Ammo
Used Clip - 2 Ammo
Keys - You need them to open some doors

You also will find weapons containing ammo.
^P
^C00
Weapons

1 - Knife
Weapon for use against weak enemies. If you run out of ammo,
you have to use the knife to defend you.

2 - Rifle
A simple rifle that uses the same ammo like
the guns of your enemies.

^P
^C00
Weapons

3 - Machine Gun
Shoots faster than a normal rifle. Holding down
the shot-button can be fun, but you should save some bullets.

4 - Chaingun
A heavy gun which shoots two bullets per shot. Very effective against big groups 
of enemies.
^P
5 - Death Cross
A special weapon against undead enemies (zombies, dead knights, flying monks). Very 
effective against them, but weak against normal enemies, like monks.
^P
^C00
Enemies
^G40,16,3
 
1 - Cultist
The worker of the butcher shop. Slow and weak.

2 - Guard
Uh-oh! Maybe he looks as weak as the first one, but his machinegun isn't!

^P
^C00
Enemies
^G40,16,3
 
3 - Psycho Doc
Cut him into two pieces and he will let you be psycho.

4 - Butcher
He never says anything, but shots faster than the other enemies.

^P
^C00
Undead Enemies
^G40,16,4
 
1 - Undead Knight
A dark creature which was awaken by occult powers.

2 - Flying Zombie
Fast and dangerous. Be warned!

^P
^C00
Other Enemies

In some levels you will confront some other enemies - bosses. You will have to think 
yourself about their end ;)


Now, go get them!
^E