
             STAR FLEET BBS'S 2 NEW WOLFENSTEIN GAME UPGRADES
---------------------------------------------------------------------------
ABOUT NEW FILES....
---------------------------------------------------------------------------
2 new games game 1 and 2, the name of the games will be still the same but
the levels will be difrent, the whole look, the plans of each floor will be
totally dirfent, difrent bad guys! secrets passages will be difrent
also,they will not be in the same places. because the whole layout of each
floor on game 1 & 2 will be totall difrent. it took me some time to change
the 2 games. i'm working on changing the rest of the games, so look out for
those..

Have fun and good luck,some levels will be harder.....



			Don Christian

