-----------------------------------------------------------------------------
 Custom maps pack                                                    6-21-94
-----------------------------------------------------------------------------
4 new episodes.
Hints on each game are included.

-----------------------------------------------------------------------------

** Episode I. Castle Mavstein (4 levels) **

  A mixed assortment of devious mazes jam packed with angry German troops.

  Scenario:  Kill Germans, find the exit.

-----------------------------------------------------------------------------

** Episode II. Castle Blitzstein, Part 1 - Breaking In (10 levels) **

  Castle Blitzstein is designed on a 16x20 grid (as opposed to the normal
  64x64 grid) to give a "quick" game.  Because the playfield is so much
  smaller, the action is much faster and often much more dangerous.  The
  only exception is the spacious Blitzstein dungeon which can take longer
  to get out of than all the other levels combined...

  Scenario:  Storm through the castle until you get to the prison level
  where you are to rescue a captured allied spy (represented by a `power
  up.')

-----------------------------------------------------------------------------

** Episode III. Castle Blitzstein, Part 2 - Escape (10 levels) **

  The first version of Blitzstein involved breaking out.  Stay out of
  the dungeon and everything should be ok.  You may notice that some
  architectural modifications have been made since your first visit
  to the castle.

  Scenario:  This time YOU are the captured allied spy and since nobody
  will be sent to rescue you you have to break out on your own.  Should
  be a piece of cake...

-----------------------------------------------------------------------------

** Episode IV. Ochsenkopf Prison, work in progress (1 level) **

  A few demo levels of a planned ten level castle.

  Scenario:  Break into the prison, kill more Germans.

-----------------------------------------------------------------------------

------------------------
  HINTS FOR CUSTOM MAPS
------------------------


** Game I. Castle Mavstein **

Level 1:
The blue key is behind a Nazi flag secret door.  Use the blue key to get to the
chain gun.  You then need to kill Boss "Arnold" to get the gold key.  Or maybe
not...  Use the gold key to access the elevator.

Level 2:
The wood walled rooms lead in a large circle so you can proceed either right
or left after exiting the elevator to get to the blue key.  Use the blue key
to get to the gold key.  The gold key leads to the steel walled maze which
hides the elevator.

Level 3:
Find the three secret doors near the elevator.  One leads to the chain gun,
one leads to the blue key, and the third leads to the rest of the maze.
Use the blue key to get to the gold key.  Use the gold key to escape.  Beware
of the three Bosses on this level (Ghost Hitler, Bertha, and Arnold.)  You
could run away, but then you'd just be a chicken.  They CAN be stopped...

Secret Level:
There is a trick to this one.  IMMEDIATELY after exiting the elevator, STOP
and WAIT for the door to close.  Then the zombies will not be aware of your
presence and you can shoot them one by one (their return fire shouldn't even
harm you.)  If you go charging right in before the elevator door closes, be
prepared for a blood bath...


** Game II. Castle Blitzstein, Episode 1 - Breaking In **

Level 1:
No trick to it, unless you want to raid the treasure vault and get to the
secret level.  One way to get to the blue key is to shoot the first guard
who comes walking out of the locked door (run there before he gets out.)
Shoot him or another guard so that the doorway is blocked open.  Lure
Boss "Arnold" out and circle back around (use a secret door...) so you can
get the chain gun out of the treasure vault and blast "Arnold."

Level 2:
No hints.

Level 3:
There is ONLY one elevator on this level, you leave on the same one as you
came in on.

Levels 4 & 5:
No hints.

Level 6:
To get through the locked doors you must run through while they are open or
shoot a guard standing in the doorway to block the door open.

Level 7:
To get to the treasure vault, you must first get through the locked doors
as described in the previous hint.

Level 8:
No hints.

Boss Level:
Find the gold key to get into the cells.  Find the cell with a secret door.
The prisoner to be rescued is behind this secret door.

Secret Level:
There is a blue key to get through the locked doors.  Follow the lights on
the ceiling to get from door to door (after you have the key) and you will
be lead to a vault of ammunition and first aid.  Beware of mutants!


** Game III. Castle Blitzstein, Episode 2 - Escape **

Levels 1 & 2:
No hints.

Levels 3 & 4:
See hints for levels 6 and 7 of Game II.

Level 5 & 6:
No hints.

Level 7:
The elevator you arrive in is ALSO the elevator to the next level.  The other
elevator on this level leads to the secret level.

Level 8:
No hints.

Boss Level:
Kill Boss "Bertha" to get the gold key so you can get to the blue key.  Use the
blue key to escape the castle.

Secret Level:
See hints for secret level of Game II.


** Game IV. Ochsenkopf Prison, work in progress **

Level 1:
Use a secret door (follow the barking) to get to the blue key.  Use the blue
key to get the gold key.  Use the gold key to get to the elevator.

Level 2:
Getting out is easy....exploring is a little more difficult.

Level 3:
A battle royale.  Or is it?  Brains, now brawn, will keep you alive.


-------------------------------------------------------------
  ** Custom levels created by The Maverick  [70671,1524] **

        Call Maverick's Quodtegitur BBS (209) 233-7835
-------------------------------------------------------------

