     Five more levels of mayhem for Wolfenstein 3-D.  The first is a VERY 
modified version of good 'ol Episode 1 Level 1 just so you'll (think) you 
know your way around.  The remaining four levels are designed from scratch 
for your blasting pleasure.  All secret doors are clearly marked because I 
HATE to slide down every wall to find those pesky things (I guess they're not 
so secret then, eh?).  If you happen to run up against any GHOSTS that you 
find you can't shake, remember, they can be boxed in the room where you found 
them if you use the PUSHWALLS wisely.  
     All levels designed by Steve Barber except level four by Brandon Kraus.
