
                           S H A N K E N S T E I N

    Description:

    Shankenstein is a collection of 6 new episodes, a total of 60 new
    floors, for use by registered owners of Wolfenstein 3D (TM).  These
    levels have been "playtested" by an experienced Wolfer using the most
    difficult level of play.


    Address:

        SHANKENSTEIN
        13700 W. Middletown Rd.
        Salem, Ohio  44460
        U.S.A.
