
Castle Wolfenstein 3-D New Game Map

10 totally new levels for the first episode of Castle Wolfenstein 3-D.
Don't be alarmed if you go to play games 2-3 or 2-6 if you have them. I
have disabled the maps to those versions in these files.

These new floors for the most part are more complex than the originals. The      
                              
average playing time on most (not all) of them was close to 20 minutes. 
Considering I knew where everything was it will probably take you a bit longer
to complete each level. <Grin> This set of floors does not contain a 
"secret level" as such. I opted for a linear progression from level 1 to 10,
however the program still shows that level 9 is a secret level when (if) you
complete it and just gives you a completion bonus. Sorry about that. So for
this set at least you don't have to worry about finding a secret level. I've
also discovered a nifty little trick that I'm sure is going to have you 
cursing my name, but I won't tell you where it is! I'll let you find it
yourself. <Grin>
                                    
The self-running demo will also be affected by my changes to the file. Don't
panic, by restoring the original files the demo will be returned to normal.

One word of advice I'll pass along: SAVE THE GAME OFTEN.

I hope you enjoy the new challenge.                                    

                                    Keith Heitmann, Prodigy #GVXV90A

