^P
^C2d Wolfmods II
^G40,16,5

^C10Fumbling through hundreds of different Wolfenstein mods, I discovered a bunch 
of features that I loved, great graphics and maps, full-screen capacity, and perusing 
them awhile inspired me to come up with a game that would incorporate the best of 
what I had seen into one program, and this resulted in Wolfmods II.

^P
^C2d Wolfmods II-Story
^G40,16,5

^C10You are Captain Zoom, secret army agent, who has become trapped in a faraway 
land, filled with formidable adversaries who are quick-striking and intelligent. 
You must fight your way to escape. It won't be easy as you venture through level 
after level of complex situations. Good luck in your adventure! Create your own story 
as you go along!

^P
^C2d Wolfmods II-Features

^C10Independent Intro Screen
Ceiling and Floor Textures
Full Screen Capacity
Directional Sprites
Animated Objects
Inter Mission Screens
Bobbing gun
Destructible Columns (spacebar)

^P
^C2d Wolfmods II-Credits

^C2b Wolfmods II is a mod by Gary Acord of id's Wolfenstein 3D. The .exe file was 
created by Michael Collin. Additional art is from Mr. Choi. Help with maps, beta-testing 
and distribution-Brian Lowe.

^C2bI used Floedit, Mapedit 7.2 and 8.4, Bill Kirby's Wolfedit, ChaosEdit, Varsity, 
Deluxe Animation, and Paintbrush to create Wolfmods II.

^P
^C2d Wolfmods II-Conclusion
^G40,16,5

^C10Try out all the other Acord Games: Wolfmods, Strange Worlds, Kozmik Zones, Supermod 
3D, Wolfhell, Super Wolfhell & Monster Land. Download them from Acord Games Website.

^C2bAcordgames.webstarts.com
^C10Gary Acord
^C2bacordgames@juno.com

^E
